<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommuneSeeder extends Seeder
{
    public function run(): void
    {
        $communes = [
            ['wilaya_id' => 1, 'name_ar' => 'أدرار'],
            ['wilaya_id' => 1, 'name_ar' => 'اقبلي'],
            ['wilaya_id' => 1, 'name_ar' => 'أولف'],
            ['wilaya_id' => 1, 'name_ar' => 'بودة'],
            ['wilaya_id' => 1, 'name_ar' => 'فنوغيل'],
            ['wilaya_id' => 1, 'name_ar' => 'إن زغمير'],
            ['wilaya_id' => 1, 'name_ar' => 'أولاد أحمد تيمي'],
            ['wilaya_id' => 1, 'name_ar' => 'رقان'],
            ['wilaya_id' => 1, 'name_ar' => 'سالي'],
            ['wilaya_id' => 1, 'name_ar' => 'السبع'],
            ['wilaya_id' => 1, 'name_ar' => 'تامنطيط'],
            ['wilaya_id' => 1, 'name_ar' => 'تامست'],
            ['wilaya_id' => 1, 'name_ar' => 'تيمقتن'],
            ['wilaya_id' => 1, 'name_ar' => 'تيت'],
            ['wilaya_id' => 1, 'name_ar' => 'تسابيت'],
            ['wilaya_id' => 1, 'name_ar' => 'زاوية كنتة'],
            ['wilaya_id' => 2, 'name_ar' => 'أبو الحسن'],
            ['wilaya_id' => 2, 'name_ar' => 'عين مران'],
            ['wilaya_id' => 2, 'name_ar' => 'بنايرية'],
            ['wilaya_id' => 2, 'name_ar' => 'بني بوعتاب'],
            ['wilaya_id' => 2, 'name_ar' => 'بني حواء'],
            ['wilaya_id' => 2, 'name_ar' => 'بني راشد'],
            ['wilaya_id' => 2, 'name_ar' => 'بوقادير'],
            ['wilaya_id' => 2, 'name_ar' => 'بوزغاية'],
            ['wilaya_id' => 2, 'name_ar' => 'بريرة'],
            ['wilaya_id' => 2, 'name_ar' => 'الشطية'],
            ['wilaya_id' => 2, 'name_ar' => 'الشلف'],
            ['wilaya_id' => 2, 'name_ar' => 'الظهرة'],
            ['wilaya_id' => 2, 'name_ar' => 'الحجاج'],
            ['wilaya_id' => 2, 'name_ar' => 'الكريمية'],
            ['wilaya_id' => 2, 'name_ar' => 'المرسى'],
            ['wilaya_id' => 2, 'name_ar' => 'حرشون'],
            ['wilaya_id' => 2, 'name_ar' => 'الهرانفة'],
            ['wilaya_id' => 2, 'name_ar' => 'الأبيض مجاجة'],
            ['wilaya_id' => 2, 'name_ar' => 'مصدق'],
            ['wilaya_id' => 2, 'name_ar' => 'وادي الفضة'],
            ['wilaya_id' => 2, 'name_ar' => 'وادي قوسين'],
            ['wilaya_id' => 2, 'name_ar' => 'وادي سلي'],
            ['wilaya_id' => 2, 'name_ar' => 'أولاد عباس'],
            ['wilaya_id' => 2, 'name_ar' => 'أولاد بن عبد القادر'],
            ['wilaya_id' => 2, 'name_ar' => 'أولاد فارس'],
            ['wilaya_id' => 2, 'name_ar' => 'أم الدروع'],
            ['wilaya_id' => 2, 'name_ar' => 'سنجاس'],
            ['wilaya_id' => 2, 'name_ar' => 'سيدي عبد الرحمن'],
            ['wilaya_id' => 2, 'name_ar' => 'سيدي عكاشة'],
            ['wilaya_id' => 2, 'name_ar' => 'الصبحة'],
            ['wilaya_id' => 2, 'name_ar' => 'تاجنة'],
            ['wilaya_id' => 2, 'name_ar' => 'تلعصة'],
            ['wilaya_id' => 2, 'name_ar' => 'تاوقريت'],
            ['wilaya_id' => 2, 'name_ar' => 'تنس'],
            ['wilaya_id' => 2, 'name_ar' => 'الزبوجة'],
            ['wilaya_id' => 3, 'name_ar' => 'الأغواط'],
            ['wilaya_id' => 3, 'name_ar' => 'أفلو'],
            ['wilaya_id' => 3, 'name_ar' => 'عين ماضي'],
            ['wilaya_id' => 3, 'name_ar' => 'بيضاء برج'],
            ['wilaya_id' => 3, 'name_ar' => 'بريدة'],
            ['wilaya_id' => 3, 'name_ar' => 'الغيشة'],
            ['wilaya_id' => 3, 'name_ar' => 'الحاج مشري'],
            ['wilaya_id' => 3, 'name_ar' => 'حاسي الدلاعة'],
            ['wilaya_id' => 3, 'name_ar' => 'حاسي الرمل'],
            ['wilaya_id' => 3, 'name_ar' => 'الخنق'],
            ['wilaya_id' => 3, 'name_ar' => 'قلتة سيدي سعد'],
            ['wilaya_id' => 3, 'name_ar' => 'قصر الحيران'],
            ['wilaya_id' => 3, 'name_ar' => 'وادي مرة'],
            ['wilaya_id' => 3, 'name_ar' => 'وادي مزي'],
            ['wilaya_id' => 3, 'name_ar' => 'البيضاء'],
            ['wilaya_id' => 3, 'name_ar' => 'سيدي بوزيد'],
            ['wilaya_id' => 3, 'name_ar' => 'سيدي مخلوف'],
            ['wilaya_id' => 3, 'name_ar' => 'تاجموت'],
            ['wilaya_id' => 3, 'name_ar' => 'تاويالة'],
            ['wilaya_id' => 3, 'name_ar' => 'تاجرونة'],
            ['wilaya_id' => 4, 'name_ar' => 'أم البواقي'],
            ['wilaya_id' => 4, 'name_ar' => 'عين البيضاء'],
            ['wilaya_id' => 4, 'name_ar' => 'عين فكرون'],
            ['wilaya_id' => 4, 'name_ar' => 'عين كرشة'],
            ['wilaya_id' => 4, 'name_ar' => 'عين مليلة'],
            ['wilaya_id' => 4, 'name_ar' => 'عين الزيتون'],
            ['wilaya_id' => 4, 'name_ar' => 'عامرية'],
            ['wilaya_id' => 4, 'name_ar' => 'بئر الشهداء'],
            ['wilaya_id' => 4, 'name_ar' => 'بحير الشرقي'],
            ['wilaya_id' => 4, 'name_ar' => 'بلالة'],
            ['wilaya_id' => 4, 'name_ar' => 'بوغرارة سعودي'],
            ['wilaya_id' => 4, 'name_ar' => 'بريش'],
            ['wilaya_id' => 4, 'name_ar' => 'الضلعة'],
            ['wilaya_id' => 4, 'name_ar' => 'فكرينة'],
            ['wilaya_id' => 4, 'name_ar' => 'الجازية'],
            ['wilaya_id' => 4, 'name_ar' => 'هنشير تومغني'],
            ['wilaya_id' => 4, 'name_ar' => 'مسكيانة'],
            ['wilaya_id' => 4, 'name_ar' => 'وادي نيني'],
            ['wilaya_id' => 4, 'name_ar' => 'أولاد قاسم'],
            ['wilaya_id' => 4, 'name_ar' => 'أولاد حملة'],
            ['wilaya_id' => 4, 'name_ar' => 'أولاد زواوي'],
            ['wilaya_id' => 4, 'name_ar' => 'قصر الصبيحي'],
            ['wilaya_id' => 4, 'name_ar' => 'الرحية'],
            ['wilaya_id' => 4, 'name_ar' => 'سوق نعمان'],
            ['wilaya_id' => 4, 'name_ar' => 'تارمونت'],
            ['wilaya_id' => 4, 'name_ar' => 'زولام'],
            ['wilaya_id' => 5, 'name_ar' => 'باتنة'],
            ['wilaya_id' => 5, 'name_ar' => 'عين جاسر'],
            ['wilaya_id' => 5, 'name_ar' => 'عين التوتة'],
            ['wilaya_id' => 5, 'name_ar' => 'عين ياقوت'],
            ['wilaya_id' => 5, 'name_ar' => 'أريس'],
            ['wilaya_id' => 5, 'name_ar' => 'بريكة'],
            ['wilaya_id' => 5, 'name_ar' => 'بوزينة'],
            ['wilaya_id' => 5, 'name_ar' => 'بومية'],
            ['wilaya_id' => 5, 'name_ar' => 'بوزينة'],
            ['wilaya_id' => 5, 'name_ar' => 'الشمرة'],
            ['wilaya_id' => 5, 'name_ar' => 'الجزار'],
            ['wilaya_id' => 5, 'name_ar' => 'القيقبة'],
            ['wilaya_id' => 5, 'name_ar' => 'المعذر'],
            ['wilaya_id' => 5, 'name_ar' => 'المنعة'],
            ['wilaya_id' => 5, 'name_ar' => 'وادي الماء'],
            ['wilaya_id' => 5, 'name_ar' => 'وادي الشعبة'],
            ['wilaya_id' => 5, 'name_ar' => 'أولاد عمار'],
            ['wilaya_id' => 5, 'name_ar' => 'أولاد فاضل'],
            ['wilaya_id' => 5, 'name_ar' => 'أولاد سلام'],
            ['wilaya_id' => 5, 'name_ar' => 'أولاد سي سليمان'],
            ['wilaya_id' => 5, 'name_ar' => 'سفيان'],
            ['wilaya_id' => 5, 'name_ar' => 'تازولت'],
            ['wilaya_id' => 5, 'name_ar' => 'تيمقاد'],
            ['wilaya_id' => 5, 'name_ar' => 'زانة البيضاء'],
            ['wilaya_id' => 6, 'name_ar' => 'بجاية'],
            ['wilaya_id' => 6, 'name_ar' => 'أدكار'],
            ['wilaya_id' => 6, 'name_ar' => 'أقبو'],
            ['wilaya_id' => 6, 'name_ar' => 'أمالو'],
            ['wilaya_id' => 6, 'name_ar' => 'أميزور'],
            ['wilaya_id' => 6, 'name_ar' => 'أوقاس'],
            ['wilaya_id' => 6, 'name_ar' => 'برباشة'],
            ['wilaya_id' => 6, 'name_ar' => 'بني جليل'],
            ['wilaya_id' => 6, 'name_ar' => 'بني مليكش'],
            ['wilaya_id' => 6, 'name_ar' => 'بني معوش'],
            ['wilaya_id' => 6, 'name_ar' => 'بوخليفة'],
            ['wilaya_id' => 6, 'name_ar' => 'بوحمزة'],
            ['wilaya_id' => 6, 'name_ar' => 'درقينة'],
            ['wilaya_id' => 6, 'name_ar' => 'الفلاي'],
            ['wilaya_id' => 6, 'name_ar' => 'إغرام'],
            ['wilaya_id' => 6, 'name_ar' => 'إغيل علي'],
            ['wilaya_id' => 6, 'name_ar' => 'خراطة'],
            ['wilaya_id' => 6, 'name_ar' => 'كنديرة'],
            ['wilaya_id' => 6, 'name_ar' => 'القصر'],
            ['wilaya_id' => 6, 'name_ar' => 'ملبو'],
            ['wilaya_id' => 6, 'name_ar' => 'أوزلاقن'],
            ['wilaya_id' => 6, 'name_ar' => 'صدوق'],
            ['wilaya_id' => 6, 'name_ar' => 'سوق الاثنين'],
            ['wilaya_id' => 6, 'name_ar' => 'تالة حمزة'],
            ['wilaya_id' => 6, 'name_ar' => 'تيمزريت'],
            ['wilaya_id' => 6, 'name_ar' => 'توجة'],
            ['wilaya_id' => 7, 'name_ar' => 'بسكرة'],
            ['wilaya_id' => 7, 'name_ar' => 'عين الناقة'],
            ['wilaya_id' => 7, 'name_ar' => 'عين زعطوط'],
            ['wilaya_id' => 7, 'name_ar' => 'بوشقرون'],
            ['wilaya_id' => 7, 'name_ar' => 'برانيس'],
            ['wilaya_id' => 7, 'name_ar' => 'الفيض'],
            ['wilaya_id' => 7, 'name_ar' => 'الحاجب'],
            ['wilaya_id' => 7, 'name_ar' => 'الخنقة'],
            ['wilaya_id' => 7, 'name_ar' => 'ليشانة'],
            ['wilaya_id' => 7, 'name_ar' => 'مشونش'],
            ['wilaya_id' => 7, 'name_ar' => 'مليلي'],
            ['wilaya_id' => 7, 'name_ar' => 'أوماش'],
            ['wilaya_id' => 7, 'name_ar' => 'سيدي عقبة'],
            ['wilaya_id' => 7, 'name_ar' => 'سيدي خالد'],
            ['wilaya_id' => 7, 'name_ar' => 'طولقة'],
            ['wilaya_id' => 7, 'name_ar' => 'زريبة الوادي'],
            ['wilaya_id' => 8, 'name_ar' => 'بشار'],
            ['wilaya_id' => 8, 'name_ar' => 'العبادلة'],
            ['wilaya_id' => 8, 'name_ar' => 'بني ونيف'],
            ['wilaya_id' => 8, 'name_ar' => 'القنادسة'],
            ['wilaya_id' => 8, 'name_ar' => 'لحمر'],
            ['wilaya_id' => 8, 'name_ar' => 'مريجة'],
            ['wilaya_id' => 8, 'name_ar' => 'موغل'],
            ['wilaya_id' => 8, 'name_ar' => 'تاغيت'],
            ['wilaya_id' => 9, 'name_ar' => 'البليدة'],
            ['wilaya_id' => 9, 'name_ar' => 'بني تامو'],
            ['wilaya_id' => 9, 'name_ar' => 'بني مراد'],
            ['wilaya_id' => 9, 'name_ar' => 'بوفاريك'],
            ['wilaya_id' => 9, 'name_ar' => 'بوقرة'],
            ['wilaya_id' => 9, 'name_ar' => 'بوعرفة'],
            ['wilaya_id' => 9, 'name_ar' => 'بوعينان'],
            ['wilaya_id' => 9, 'name_ar' => 'الشبلي'],
            ['wilaya_id' => 9, 'name_ar' => 'الشريعة'],
            ['wilaya_id' => 9, 'name_ar' => 'حمام ملوان'],
            ['wilaya_id' => 9, 'name_ar' => 'الأربعاء'],
            ['wilaya_id' => 9, 'name_ar' => 'مفتاح'],
            ['wilaya_id' => 9, 'name_ar' => 'موزاية'],
            ['wilaya_id' => 9, 'name_ar' => 'أولاد سلامة'],
            ['wilaya_id' => 9, 'name_ar' => 'أولاد يعيش'],
            ['wilaya_id' => 9, 'name_ar' => 'الشفة'],
            ['wilaya_id' => 9, 'name_ar' => 'الصومعة'],
            ['wilaya_id' => 9, 'name_ar' => 'وادي العلايق'],
            ['wilaya_id' => 10, 'name_ar' => 'البويرة'],
            ['wilaya_id' => 10, 'name_ar' => 'أهل القصر'],
            ['wilaya_id' => 10, 'name_ar' => 'عين بسام'],
            ['wilaya_id' => 10, 'name_ar' => 'عين الحجر'],
            ['wilaya_id' => 10, 'name_ar' => 'عين الترك'],
            ['wilaya_id' => 10, 'name_ar' => 'آيت لعزيز'],
            ['wilaya_id' => 10, 'name_ar' => 'بشلول'],
            ['wilaya_id' => 10, 'name_ar' => 'بئر غبالو'],
            ['wilaya_id' => 10, 'name_ar' => 'برج أوخريص'],
            ['wilaya_id' => 10, 'name_ar' => 'بوكرام'],
            ['wilaya_id' => 10, 'name_ar' => 'ديرة'],
            ['wilaya_id' => 10, 'name_ar' => 'الهاشمية'],
            ['wilaya_id' => 10, 'name_ar' => 'الحاكمية'],
            ['wilaya_id' => 10, 'name_ar' => 'الخبوزية'],
            ['wilaya_id' => 10, 'name_ar' => 'الأخضرية'],
            ['wilaya_id' => 10, 'name_ar' => 'المعمورة'],
            ['wilaya_id' => 10, 'name_ar' => 'قرومة'],
            ['wilaya_id' => 10, 'name_ar' => 'ريدان'],
            ['wilaya_id' => 10, 'name_ar' => 'سوق الخميس'],
            ['wilaya_id' => 10, 'name_ar' => 'سور الغزلان'],
            ['wilaya_id' => 10, 'name_ar' => 'تاغزوت'],
            ['wilaya_id' => 10, 'name_ar' => 'تيكستير'],
            ['wilaya_id' => 11, 'name_ar' => 'تمنراست'],
            ['wilaya_id' => 11, 'name_ar' => 'أبلسة'],
            ['wilaya_id' => 11, 'name_ar' => 'إدلس'],
            ['wilaya_id' => 11, 'name_ar' => 'تاظروك'],
            ['wilaya_id' => 12, 'name_ar' => 'تبسة'],
            ['wilaya_id' => 12, 'name_ar' => 'عين الزرقاء'],
            ['wilaya_id' => 12, 'name_ar' => 'بئر العاتر'],
            ['wilaya_id' => 12, 'name_ar' => 'بئر الذهب'],
            ['wilaya_id' => 12, 'name_ar' => 'بئر مقدم'],
            ['wilaya_id' => 12, 'name_ar' => 'بوشبكة'],
            ['wilaya_id' => 12, 'name_ar' => 'الشريعة'],
            ['wilaya_id' => 12, 'name_ar' => 'العقلة'],
            ['wilaya_id' => 12, 'name_ar' => 'الماء الأبيض'],
            ['wilaya_id' => 12, 'name_ar' => 'المريج'],
            ['wilaya_id' => 12, 'name_ar' => 'المزرعة'],
            ['wilaya_id' => 12, 'name_ar' => 'مرسط'],
            ['wilaya_id' => 12, 'name_ar' => 'نقرين'],
            ['wilaya_id' => 12, 'name_ar' => 'ونزة'],
            ['wilaya_id' => 12, 'name_ar' => 'سطح قنطيس'],
            ['wilaya_id' => 12, 'name_ar' => 'ثليجان'],
            ['wilaya_id' => 13, 'name_ar' => 'تلمسان'],
            ['wilaya_id' => 13, 'name_ar' => 'عين فزة'],
            ['wilaya_id' => 13, 'name_ar' => 'عين غرابة'],
            ['wilaya_id' => 13, 'name_ar' => 'عين نحالة'],
            ['wilaya_id' => 13, 'name_ar' => 'عين تالوت'],
            ['wilaya_id' => 13, 'name_ar' => 'عمير'],
            ['wilaya_id' => 13, 'name_ar' => 'بني بهدل'],
            ['wilaya_id' => 13, 'name_ar' => 'بني خلاد'],
            ['wilaya_id' => 13, 'name_ar' => 'بني مستار'],
            ['wilaya_id' => 13, 'name_ar' => 'بني سنوس'],
            ['wilaya_id' => 13, 'name_ar' => 'بني ورسوس'],
            ['wilaya_id' => 13, 'name_ar' => 'بن سكران'],
            ['wilaya_id' => 13, 'name_ar' => 'بوحلو'],
            ['wilaya_id' => 13, 'name_ar' => 'شتوان'],
            ['wilaya_id' => 13, 'name_ar' => 'دار يغمراسن'],
            ['wilaya_id' => 13, 'name_ar' => 'فلاوسن'],
            ['wilaya_id' => 13, 'name_ar' => 'غزوات'],
            ['wilaya_id' => 13, 'name_ar' => 'الحناية'],
            ['wilaya_id' => 13, 'name_ar' => 'الحواجز'],
            ['wilaya_id' => 13, 'name_ar' => 'مغنية'],
            ['wilaya_id' => 13, 'name_ar' => 'منصورة'],
            ['wilaya_id' => 13, 'name_ar' => 'ندرومة'],
            ['wilaya_id' => 13, 'name_ar' => 'أولاد ميمون'],
            ['wilaya_id' => 13, 'name_ar' => 'الرمشي'],
            ['wilaya_id' => 13, 'name_ar' => 'صبرة'],
            ['wilaya_id' => 13, 'name_ar' => 'سبدو'],
            ['wilaya_id' => 13, 'name_ar' => 'سيدي مجاهد'],
            ['wilaya_id' => 13, 'name_ar' => 'سوق الاثنين'],
            ['wilaya_id' => 14, 'name_ar' => 'تيارت'],
            ['wilaya_id' => 14, 'name_ar' => 'عين بوشقيف'],
            ['wilaya_id' => 14, 'name_ar' => 'عين الذهب'],
            ['wilaya_id' => 14, 'name_ar' => 'عين الحديد'],
            ['wilaya_id' => 14, 'name_ar' => 'عين كرمس'],
            ['wilaya_id' => 14, 'name_ar' => 'بوغارة'],
            ['wilaya_id' => 14, 'name_ar' => 'شحمية'],
            ['wilaya_id' => 14, 'name_ar' => 'دحموني'],
            ['wilaya_id' => 14, 'name_ar' => 'فرندة'],
            ['wilaya_id' => 14, 'name_ar' => 'حمادية'],
            ['wilaya_id' => 14, 'name_ar' => 'قصر الشلالة'],
            ['wilaya_id' => 14, 'name_ar' => 'مدروسة'],
            ['wilaya_id' => 14, 'name_ar' => 'مغيلة'],
            ['wilaya_id' => 14, 'name_ar' => 'مهدية'],
            ['wilaya_id' => 14, 'name_ar' => 'وادي ليلي'],
            ['wilaya_id' => 14, 'name_ar' => 'رحوية'],
            ['wilaya_id' => 14, 'name_ar' => 'سوقر'],
            ['wilaya_id' => 14, 'name_ar' => 'توسنينة'],
            ['wilaya_id' => 15, 'name_ar' => 'تيزي وزو'],
            ['wilaya_id' => 15, 'name_ar' => 'أبي يوسف'],
            ['wilaya_id' => 15, 'name_ar' => 'أغريب'],
            ['wilaya_id' => 15, 'name_ar' => 'عين الحمام'],
            ['wilaya_id' => 15, 'name_ar' => 'آيت بومهدي'],
            ['wilaya_id' => 15, 'name_ar' => 'آيت محمود'],
            ['wilaya_id' => 15, 'name_ar' => 'آيت أومالو'],
            ['wilaya_id' => 15, 'name_ar' => 'آيت تودرت'],
            ['wilaya_id' => 15, 'name_ar' => 'آيت يحيى'],
            ['wilaya_id' => 15, 'name_ar' => 'آيت يحيى موسى'],
            ['wilaya_id' => 15, 'name_ar' => 'أزفون'],
            ['wilaya_id' => 15, 'name_ar' => 'عزازقة'],
            ['wilaya_id' => 15, 'name_ar' => 'بني دوالة'],
            ['wilaya_id' => 15, 'name_ar' => 'بني يني'],
            ['wilaya_id' => 15, 'name_ar' => 'بني زكي'],
            ['wilaya_id' => 15, 'name_ar' => 'بني زمنزر'],
            ['wilaya_id' => 15, 'name_ar' => 'بوزغن'],
            ['wilaya_id' => 15, 'name_ar' => 'ذراع بن خدة'],
            ['wilaya_id' => 15, 'name_ar' => 'ذراع الميزان'],
            ['wilaya_id' => 15, 'name_ar' => 'إفليسن'],
            ['wilaya_id' => 15, 'name_ar' => 'إيفرحونن'],
            ['wilaya_id' => 15, 'name_ar' => 'إيلولة أومالو'],
            ['wilaya_id' => 15, 'name_ar' => 'إيرجن'],
            ['wilaya_id' => 15, 'name_ar' => 'إعكوران'],
            ['wilaya_id' => 15, 'name_ar' => 'إيلولة'],
            ['wilaya_id' => 15, 'name_ar' => 'مقلع'],
            ['wilaya_id' => 15, 'name_ar' => 'معاتقة'],
            ['wilaya_id' => 15, 'name_ar' => 'مكيرة'],
            ['wilaya_id' => 15, 'name_ar' => 'ميزرانة'],
            ['wilaya_id' => 15, 'name_ar' => 'واسيف'],
            ['wilaya_id' => 15, 'name_ar' => 'واضية'],
            ['wilaya_id' => 15, 'name_ar' => 'ياكوران'],
            ['wilaya_id' => 16, 'name_ar' => 'الجزائر الوسطى'],
            ['wilaya_id' => 16, 'name_ar' => 'سيدي امحمد'],
            ['wilaya_id' => 16, 'name_ar' => 'المدنية'],
            ['wilaya_id' => 16, 'name_ar' => 'بلوزداد'],
            ['wilaya_id' => 16, 'name_ar' => 'باب الوادي'],
            ['wilaya_id' => 16, 'name_ar' => 'بولوغين'],
            ['wilaya_id' => 16, 'name_ar' => 'حمامات'],
            ['wilaya_id' => 16, 'name_ar' => 'رايس حميدو'],
            ['wilaya_id' => 16, 'name_ar' => 'القصبة'],
            ['wilaya_id' => 16, 'name_ar' => 'وادي قريش'],
            ['wilaya_id' => 16, 'name_ar' => 'بئر مراد رايس'],
            ['wilaya_id' => 16, 'name_ar' => 'بئر خادم'],
            ['wilaya_id' => 16, 'name_ar' => 'حيدرة'],
            ['wilaya_id' => 16, 'name_ar' => 'الأبيار'],
            ['wilaya_id' => 16, 'name_ar' => 'بن عكنون'],
            ['wilaya_id' => 16, 'name_ar' => 'بوزريعة'],
            ['wilaya_id' => 16, 'name_ar' => 'بني مسوس'],
            ['wilaya_id' => 16, 'name_ar' => 'دالي إبراهيم'],
            ['wilaya_id' => 16, 'name_ar' => 'الشراقة'],
            ['wilaya_id' => 16, 'name_ar' => 'عين البنيان'],
            ['wilaya_id' => 16, 'name_ar' => 'سطاوالي'],
            ['wilaya_id' => 16, 'name_ar' => 'زرالدة'],
            ['wilaya_id' => 16, 'name_ar' => 'المعالمة'],
            ['wilaya_id' => 16, 'name_ar' => 'السويدانية'],
            ['wilaya_id' => 16, 'name_ar' => 'الحراش'],
            ['wilaya_id' => 16, 'name_ar' => 'بوروبة'],
            ['wilaya_id' => 16, 'name_ar' => 'وادي السمار'],
            ['wilaya_id' => 16, 'name_ar' => 'باش جراح'],
            ['wilaya_id' => 16, 'name_ar' => 'المقارية'],
            ['wilaya_id' => 16, 'name_ar' => 'حسين داي'],
            ['wilaya_id' => 16, 'name_ar' => 'القبة'],
            ['wilaya_id' => 16, 'name_ar' => 'جسر قسنطينة'],
            ['wilaya_id' => 16, 'name_ar' => 'بئر توتة'],
            ['wilaya_id' => 16, 'name_ar' => 'تسالة المرجة'],
            ['wilaya_id' => 16, 'name_ar' => 'أولاد شبل'],
            ['wilaya_id' => 16, 'name_ar' => 'الدار البيضاء'],
            ['wilaya_id' => 16, 'name_ar' => 'باب الزوار'],
            ['wilaya_id' => 16, 'name_ar' => 'برج الكيفان'],
            ['wilaya_id' => 16, 'name_ar' => 'برج البحري'],
            ['wilaya_id' => 16, 'name_ar' => 'المرسى'],
            ['wilaya_id' => 16, 'name_ar' => 'عين طاية'],
            ['wilaya_id' => 16, 'name_ar' => 'هراوة'],
            ['wilaya_id' => 16, 'name_ar' => 'رويبة'],
            ['wilaya_id' => 16, 'name_ar' => 'الرغاية'],
            ['wilaya_id' => 16, 'name_ar' => 'براقي'],
            ['wilaya_id' => 16, 'name_ar' => 'الكاليتوس'],
            ['wilaya_id' => 16, 'name_ar' => 'سيدي موسى'],
            ['wilaya_id' => 17, 'name_ar' => 'الجلفة'],
            ['wilaya_id' => 17, 'name_ar' => 'عين الإبل'],
            ['wilaya_id' => 17, 'name_ar' => 'عين معبد'],
            ['wilaya_id' => 17, 'name_ar' => 'عين وسارة'],
            ['wilaya_id' => 17, 'name_ar' => 'بيرين'],
            ['wilaya_id' => 17, 'name_ar' => 'بويرة الأحداب'],
            ['wilaya_id' => 17, 'name_ar' => 'دار الشيوخ'],
            ['wilaya_id' => 17, 'name_ar' => 'دلدول'],
            ['wilaya_id' => 17, 'name_ar' => 'الإدريسية'],
            ['wilaya_id' => 17, 'name_ar' => 'فيض البطمة'],
            ['wilaya_id' => 17, 'name_ar' => 'حد الصحاري'],
            ['wilaya_id' => 17, 'name_ar' => 'حاسي بحبح'],
            ['wilaya_id' => 17, 'name_ar' => 'حاسي العش'],
            ['wilaya_id' => 17, 'name_ar' => 'حاسي فدول'],
            ['wilaya_id' => 17, 'name_ar' => 'مسعد'],
            ['wilaya_id' => 17, 'name_ar' => 'مجبارة'],
            ['wilaya_id' => 17, 'name_ar' => 'قطارة'],
            ['wilaya_id' => 17, 'name_ar' => 'سيدي بايزيد'],
            ['wilaya_id' => 17, 'name_ar' => 'سيدي لعجال'],
            ['wilaya_id' => 17, 'name_ar' => 'الشارف'],
            ['wilaya_id' => 17, 'name_ar' => 'تعظميت'],
            ['wilaya_id' => 17, 'name_ar' => 'زعفران'],
            ['wilaya_id' => 18, 'name_ar' => 'جيجل'],
            ['wilaya_id' => 18, 'name_ar' => 'بني حبيبي'],
            ['wilaya_id' => 18, 'name_ar' => 'بني ياجيس'],
            ['wilaya_id' => 18, 'name_ar' => 'بني زيد'],
            ['wilaya_id' => 18, 'name_ar' => 'بوراوي بلهادف'],
            ['wilaya_id' => 18, 'name_ar' => 'بوسيف أولاد عسكر'],
            ['wilaya_id' => 18, 'name_ar' => 'الشقفة'],
            ['wilaya_id' => 18, 'name_ar' => 'الجمعة بني حبيبي'],
            ['wilaya_id' => 18, 'name_ar' => 'العنصر'],
            ['wilaya_id' => 18, 'name_ar' => 'الميلية'],
            ['wilaya_id' => 18, 'name_ar' => 'الأمير عبد القادر'],
            ['wilaya_id' => 18, 'name_ar' => 'قاوس'],
            ['wilaya_id' => 18, 'name_ar' => 'جيملة'],
            ['wilaya_id' => 18, 'name_ar' => 'السطارة'],
            ['wilaya_id' => 18, 'name_ar' => 'سيدي عبد العزيز'],
            ['wilaya_id' => 18, 'name_ar' => 'سيدي معروف'],
            ['wilaya_id' => 18, 'name_ar' => 'طاهر'],
            ['wilaya_id' => 18, 'name_ar' => 'وجانة'],
            ['wilaya_id' => 18, 'name_ar' => 'زيامة منصورية'],
            ['wilaya_id' => 19, 'name_ar' => 'سطيف'],
            ['wilaya_id' => 19, 'name_ar' => 'عين أرنات'],
            ['wilaya_id' => 19, 'name_ar' => 'عين أزال'],
            ['wilaya_id' => 19, 'name_ar' => 'عين الكبيرة'],
            ['wilaya_id' => 19, 'name_ar' => 'عين الحجر'],
            ['wilaya_id' => 19, 'name_ar' => 'عين الروى'],
            ['wilaya_id' => 19, 'name_ar' => 'عين السبت'],
            ['wilaya_id' => 19, 'name_ar' => 'عين ولمان'],
            ['wilaya_id' => 19, 'name_ar' => 'آيت نوال مزادة'],
            ['wilaya_id' => 19, 'name_ar' => 'آيت تيزي'],
            ['wilaya_id' => 19, 'name_ar' => 'عموشة'],
            ['wilaya_id' => 19, 'name_ar' => 'بابل برج'],
            ['wilaya_id' => 19, 'name_ar' => 'بني عزيز'],
            ['wilaya_id' => 19, 'name_ar' => 'بني فودة'],
            ['wilaya_id' => 19, 'name_ar' => 'بني ورتيلان'],
            ['wilaya_id' => 19, 'name_ar' => 'بئر العرش'],
            ['wilaya_id' => 19, 'name_ar' => 'بئر حدادة'],
            ['wilaya_id' => 19, 'name_ar' => 'بوعنداس'],
            ['wilaya_id' => 19, 'name_ar' => 'بوقاعة'],
            ['wilaya_id' => 19, 'name_ar' => 'بوسلام'],
            ['wilaya_id' => 19, 'name_ar' => 'الدهامشة'],
            ['wilaya_id' => 19, 'name_ar' => 'العلمة'],
            ['wilaya_id' => 19, 'name_ar' => 'قلال'],
            ['wilaya_id' => 19, 'name_ar' => 'قجال'],
            ['wilaya_id' => 19, 'name_ar' => 'قنزات'],
            ['wilaya_id' => 19, 'name_ar' => 'حمام السخنة'],
            ['wilaya_id' => 19, 'name_ar' => 'حمام قرقور'],
            ['wilaya_id' => 19, 'name_ar' => 'ماوكلان'],
            ['wilaya_id' => 19, 'name_ar' => 'مزلوق'],
            ['wilaya_id' => 19, 'name_ar' => 'أولاد عدوان'],
            ['wilaya_id' => 19, 'name_ar' => 'أولاد صابر'],
            ['wilaya_id' => 19, 'name_ar' => 'أولاد سي أحمد'],
            ['wilaya_id' => 19, 'name_ar' => 'أولاد تبان'],
            ['wilaya_id' => 19, 'name_ar' => 'الرصفة'],
            ['wilaya_id' => 19, 'name_ar' => 'صالح باي'],
            ['wilaya_id' => 19, 'name_ar' => 'تالة إيفاسن'],
            ['wilaya_id' => 19, 'name_ar' => 'تيزي نبشار'],
            ['wilaya_id' => 20, 'name_ar' => 'سعيدة'],
            ['wilaya_id' => 20, 'name_ar' => 'عين الحجر'],
            ['wilaya_id' => 20, 'name_ar' => 'عين السلطان'],
            ['wilaya_id' => 20, 'name_ar' => 'دوي ثابت'],
            ['wilaya_id' => 20, 'name_ar' => 'الحساسنة'],
            ['wilaya_id' => 20, 'name_ar' => 'حمام ربي'],
            ['wilaya_id' => 20, 'name_ar' => 'أولاد خالد'],
            ['wilaya_id' => 20, 'name_ar' => 'أولاد إبراهيم'],
            ['wilaya_id' => 20, 'name_ar' => 'سيدي أحمد'],
            ['wilaya_id' => 20, 'name_ar' => 'سيدي بوبكر'],
            ['wilaya_id' => 20, 'name_ar' => 'سيدي عمر'],
            ['wilaya_id' => 20, 'name_ar' => 'تيرسين'],
            ['wilaya_id' => 20, 'name_ar' => 'يوب'],
            ['wilaya_id' => 21, 'name_ar' => 'سكيكدة'],
            ['wilaya_id' => 21, 'name_ar' => 'عين بوزيان'],
            ['wilaya_id' => 21, 'name_ar' => 'عين قشرة'],
            ['wilaya_id' => 21, 'name_ar' => 'عين زويت'],
            ['wilaya_id' => 21, 'name_ar' => 'عزاميل'],
            ['wilaya_id' => 21, 'name_ar' => 'بن عزوز'],
            ['wilaya_id' => 21, 'name_ar' => 'بني بشير'],
            ['wilaya_id' => 21, 'name_ar' => 'بني ولبان'],
            ['wilaya_id' => 21, 'name_ar' => 'بني زيد'],
            ['wilaya_id' => 21, 'name_ar' => 'بوشطاطة'],
            ['wilaya_id' => 21, 'name_ar' => 'شرائع'],
            ['wilaya_id' => 21, 'name_ar' => 'القل'],
            ['wilaya_id' => 21, 'name_ar' => 'الغدير'],
            ['wilaya_id' => 21, 'name_ar' => 'الحروش'],
            ['wilaya_id' => 21, 'name_ar' => 'جندل'],
            ['wilaya_id' => 21, 'name_ar' => 'كركرة'],
            ['wilaya_id' => 21, 'name_ar' => 'المرسى'],
            ['wilaya_id' => 21, 'name_ar' => 'مجاز الدشيش'],
            ['wilaya_id' => 21, 'name_ar' => 'أولاد عطية'],
            ['wilaya_id' => 21, 'name_ar' => 'أولاد حبابة'],
            ['wilaya_id' => 21, 'name_ar' => 'رمضان جمال'],
            ['wilaya_id' => 21, 'name_ar' => 'صالح بوالشعور'],
            ['wilaya_id' => 21, 'name_ar' => 'سيدي مزغيش'],
            ['wilaya_id' => 21, 'name_ar' => 'تمالوس'],
            ['wilaya_id' => 21, 'name_ar' => 'الولجة بولبلوط'],
            ['wilaya_id' => 21, 'name_ar' => 'زردازة'],
            ['wilaya_id' => 22, 'name_ar' => 'سيدي بلعباس'],
            ['wilaya_id' => 22, 'name_ar' => 'عين البرد'],
            ['wilaya_id' => 22, 'name_ar' => 'عين قادة'],
            ['wilaya_id' => 22, 'name_ar' => 'عين الثريد'],
            ['wilaya_id' => 22, 'name_ar' => 'عين تالوت'],
            ['wilaya_id' => 22, 'name_ar' => 'العمارنة'],
            ['wilaya_id' => 22, 'name_ar' => 'بني تالة'],
            ['wilaya_id' => 22, 'name_ar' => 'بن عشيبة شلية'],
            ['wilaya_id' => 22, 'name_ar' => 'بلعربي'],
            ['wilaya_id' => 22, 'name_ar' => 'بوخنفيس'],
            ['wilaya_id' => 22, 'name_ar' => 'حاسي دحو'],
            ['wilaya_id' => 22, 'name_ar' => 'الحصيبة'],
            ['wilaya_id' => 22, 'name_ar' => 'مرحوم'],
            ['wilaya_id' => 22, 'name_ar' => 'مولاي سليسن'],
            ['wilaya_id' => 22, 'name_ar' => 'مصطفى بن إبراهيم'],
            ['wilaya_id' => 22, 'name_ar' => 'رجم دموش'],
            ['wilaya_id' => 22, 'name_ar' => 'سيدي علي بن يوب'],
            ['wilaya_id' => 22, 'name_ar' => 'سيدي علي بوسيدي'],
            ['wilaya_id' => 22, 'name_ar' => 'سيدي براهيم'],
            ['wilaya_id' => 22, 'name_ar' => 'سيدي حمادوش'],
            ['wilaya_id' => 22, 'name_ar' => 'سيدي خالد'],
            ['wilaya_id' => 22, 'name_ar' => 'سيدي لحسن'],
            ['wilaya_id' => 22, 'name_ar' => 'سيدي شعيب'],
            ['wilaya_id' => 22, 'name_ar' => 'سيدي يعقوب'],
            ['wilaya_id' => 22, 'name_ar' => 'تلاغ'],
            ['wilaya_id' => 22, 'name_ar' => 'تلموني'],
            ['wilaya_id' => 22, 'name_ar' => 'تنيرة'],
            ['wilaya_id' => 22, 'name_ar' => 'تسالة'],
            ['wilaya_id' => 22, 'name_ar' => 'تيزي'],
            ['wilaya_id' => 23, 'name_ar' => 'عنابة'],
            ['wilaya_id' => 23, 'name_ar' => 'برحال'],
            ['wilaya_id' => 23, 'name_ar' => 'البوني'],
            ['wilaya_id' => 23, 'name_ar' => 'شطايبي'],
            ['wilaya_id' => 23, 'name_ar' => 'الحجار'],
            ['wilaya_id' => 23, 'name_ar' => 'سيدي عمار'],
            ['wilaya_id' => 23, 'name_ar' => 'سرايدي'],
            ['wilaya_id' => 23, 'name_ar' => 'التريعات'],
            ['wilaya_id' => 24, 'name_ar' => 'قالمة'],
            ['wilaya_id' => 24, 'name_ar' => 'عين بن بيضاء'],
            ['wilaya_id' => 24, 'name_ar' => 'عين مخلوف'],
            ['wilaya_id' => 24, 'name_ar' => 'عين رقادة'],
            ['wilaya_id' => 24, 'name_ar' => 'عين العربي'],
            ['wilaya_id' => 24, 'name_ar' => 'بوشقوف'],
            ['wilaya_id' => 24, 'name_ar' => 'بومهرة أحمد'],
            ['wilaya_id' => 24, 'name_ar' => 'بني مزلين'],
            ['wilaya_id' => 24, 'name_ar' => 'بوعاطي محمود'],
            ['wilaya_id' => 24, 'name_ar' => 'بوحشانة'],
            ['wilaya_id' => 24, 'name_ar' => 'الدهوارة'],
            ['wilaya_id' => 24, 'name_ar' => 'الفجوج'],
            ['wilaya_id' => 24, 'name_ar' => 'حمام دباغ'],
            ['wilaya_id' => 24, 'name_ar' => 'حمام النبائل'],
            ['wilaya_id' => 24, 'name_ar' => 'هيليوبوليس'],
            ['wilaya_id' => 24, 'name_ar' => 'هواري بومدين'],
            ['wilaya_id' => 24, 'name_ar' => 'مجاز عمار'],
            ['wilaya_id' => 24, 'name_ar' => 'مجاز الصفاء'],
            ['wilaya_id' => 24, 'name_ar' => 'نشماية'],
            ['wilaya_id' => 24, 'name_ar' => 'وادي الزناتي'],
            ['wilaya_id' => 24, 'name_ar' => 'أولاد حبابة'],
            ['wilaya_id' => 24, 'name_ar' => 'الركنية'],
            ['wilaya_id' => 24, 'name_ar' => 'سلاوة عنونة'],
            ['wilaya_id' => 24, 'name_ar' => 'تاملوكة'],
            ['wilaya_id' => 25, 'name_ar' => 'قسنطينة'],
            ['wilaya_id' => 25, 'name_ar' => 'عين عبيد'],
            ['wilaya_id' => 25, 'name_ar' => 'عين سمارة'],
            ['wilaya_id' => 25, 'name_ar' => 'بني حميدان'],
            ['wilaya_id' => 25, 'name_ar' => 'ديدوش مراد'],
            ['wilaya_id' => 25, 'name_ar' => 'الخروب'],
            ['wilaya_id' => 25, 'name_ar' => 'حامة بوزيان'],
            ['wilaya_id' => 25, 'name_ar' => 'ابن زياد'],
            ['wilaya_id' => 25, 'name_ar' => 'أولاد رحمون'],
            ['wilaya_id' => 25, 'name_ar' => 'زيغود يوسف'],
            ['wilaya_id' => 26, 'name_ar' => 'المدية'],
            ['wilaya_id' => 26, 'name_ar' => 'عين بوسيف'],
            ['wilaya_id' => 26, 'name_ar' => 'عزيز'],
            ['wilaya_id' => 26, 'name_ar' => 'بني سليمان'],
            ['wilaya_id' => 26, 'name_ar' => 'بني يحيى'],
            ['wilaya_id' => 26, 'name_ar' => 'بئر بن عابد'],
            ['wilaya_id' => 26, 'name_ar' => 'بوغار'],
            ['wilaya_id' => 26, 'name_ar' => 'بوغزول'],
            ['wilaya_id' => 26, 'name_ar' => 'بوشراحيل'],
            ['wilaya_id' => 26, 'name_ar' => 'شلالة العذاورة'],
            ['wilaya_id' => 26, 'name_ar' => 'الشهبونية'],
            ['wilaya_id' => 26, 'name_ar' => 'دراق'],
            ['wilaya_id' => 26, 'name_ar' => 'البرواقية'],
            ['wilaya_id' => 26, 'name_ar' => 'الحوضان'],
            ['wilaya_id' => 26, 'name_ar' => 'قصر البخاري'],
            ['wilaya_id' => 26, 'name_ar' => 'مغراوة'],
            ['wilaya_id' => 26, 'name_ar' => 'مجانة'],
            ['wilaya_id' => 26, 'name_ar' => 'أولاد عنتر'],
            ['wilaya_id' => 26, 'name_ar' => 'أولاد دايد'],
            ['wilaya_id' => 26, 'name_ar' => 'أولاد إبراهيم'],
            ['wilaya_id' => 26, 'name_ar' => 'أولاد معرف'],
            ['wilaya_id' => 26, 'name_ar' => 'أولاد ميمون'],
            ['wilaya_id' => 26, 'name_ar' => 'أولاد هلال'],
            ['wilaya_id' => 26, 'name_ar' => 'الربعية'],
            ['wilaya_id' => 26, 'name_ar' => 'سيدي دامد'],
            ['wilaya_id' => 26, 'name_ar' => 'سيدي نعمان'],
            ['wilaya_id' => 26, 'name_ar' => 'سي المحجوب'],
            ['wilaya_id' => 26, 'name_ar' => 'سواقي'],
            ['wilaya_id' => 26, 'name_ar' => 'تابلاط'],
            ['wilaya_id' => 26, 'name_ar' => 'تارمونت'],
            ['wilaya_id' => 26, 'name_ar' => 'تيزي مهدي'],
            ['wilaya_id' => 26, 'name_ar' => 'وزرة'],
            ['wilaya_id' => 27, 'name_ar' => 'مستغانم'],
            ['wilaya_id' => 27, 'name_ar' => 'أشعاشة'],
            ['wilaya_id' => 27, 'name_ar' => 'عين بودينار'],
            ['wilaya_id' => 27, 'name_ar' => 'عين نويسي'],
            ['wilaya_id' => 27, 'name_ar' => 'عين سيدي شريف'],
            ['wilaya_id' => 27, 'name_ar' => 'عين تادلس'],
            ['wilaya_id' => 27, 'name_ar' => 'بوقيرات'],
            ['wilaya_id' => 27, 'name_ar' => 'فرناكة'],
            ['wilaya_id' => 27, 'name_ar' => 'حاسي ماماش'],
            ['wilaya_id' => 27, 'name_ar' => 'خضرة'],
            ['wilaya_id' => 27, 'name_ar' => 'خير الدين'],
            ['wilaya_id' => 27, 'name_ar' => 'منصورة'],
            ['wilaya_id' => 27, 'name_ar' => 'مزغران'],
            ['wilaya_id' => 27, 'name_ar' => 'نكمارية'],
            ['wilaya_id' => 27, 'name_ar' => 'وادي الخير'],
            ['wilaya_id' => 27, 'name_ar' => 'أولاد بوغالم'],
            ['wilaya_id' => 27, 'name_ar' => 'أولاد مع الله'],
            ['wilaya_id' => 27, 'name_ar' => 'سيدي علي'],
            ['wilaya_id' => 27, 'name_ar' => 'سيدي بلعطار'],
            ['wilaya_id' => 27, 'name_ar' => 'سيدي لخضر'],
            ['wilaya_id' => 27, 'name_ar' => 'سوافلية'],
            ['wilaya_id' => 27, 'name_ar' => 'صفصاف'],
            ['wilaya_id' => 27, 'name_ar' => 'سيدي الشحمي'],
            ['wilaya_id' => 27, 'name_ar' => 'تازوغرت'],
            ['wilaya_id' => 28, 'name_ar' => 'المسيلة'],
            ['wilaya_id' => 28, 'name_ar' => 'عين الحجل'],
            ['wilaya_id' => 28, 'name_ar' => 'عين الملح'],
            ['wilaya_id' => 28, 'name_ar' => 'عين خضراء'],
            ['wilaya_id' => 28, 'name_ar' => 'عين الريش'],
            ['wilaya_id' => 28, 'name_ar' => 'بني يلمان'],
            ['wilaya_id' => 28, 'name_ar' => 'بنزوه'],
            ['wilaya_id' => 28, 'name_ar' => 'بوسعادة'],
            ['wilaya_id' => 28, 'name_ar' => 'بوطي السايح'],
            ['wilaya_id' => 28, 'name_ar' => 'الشلال'],
            ['wilaya_id' => 28, 'name_ar' => 'الدهاهنة'],
            ['wilaya_id' => 28, 'name_ar' => 'الهامل'],
            ['wilaya_id' => 28, 'name_ar' => 'المعاريف'],
            ['wilaya_id' => 28, 'name_ar' => 'حمام الضلعة'],
            ['wilaya_id' => 28, 'name_ar' => 'خبانة'],
            ['wilaya_id' => 28, 'name_ar' => 'خوبانة'],
            ['wilaya_id' => 28, 'name_ar' => 'مناعة'],
            ['wilaya_id' => 28, 'name_ar' => 'مقرة'],
            ['wilaya_id' => 28, 'name_ar' => 'محمد بوضياف'],
            ['wilaya_id' => 28, 'name_ar' => 'أولاد عدي لقبالة'],
            ['wilaya_id' => 28, 'name_ar' => 'أولاد دراج'],
            ['wilaya_id' => 28, 'name_ar' => 'أولاد غانم'],
            ['wilaya_id' => 28, 'name_ar' => 'أولاد ماضي'],
            ['wilaya_id' => 28, 'name_ar' => 'أولاد منصور'],
            ['wilaya_id' => 28, 'name_ar' => 'أولاد سيدي إبراهيم'],
            ['wilaya_id' => 28, 'name_ar' => 'أولاد سليمان'],
            ['wilaya_id' => 28, 'name_ar' => 'سيدي عيسى'],
            ['wilaya_id' => 28, 'name_ar' => 'سيدي هجرس'],
            ['wilaya_id' => 28, 'name_ar' => 'سليم'],
            ['wilaya_id' => 28, 'name_ar' => 'تارمونت'],
            ['wilaya_id' => 28, 'name_ar' => 'تامسة'],
            ['wilaya_id' => 28, 'name_ar' => 'تارمونت'],
            ['wilaya_id' => 28, 'name_ar' => 'ونوغة'],
            ['wilaya_id' => 29, 'name_ar' => 'معسكر'],
            ['wilaya_id' => 29, 'name_ar' => 'عين فكان'],
            ['wilaya_id' => 29, 'name_ar' => 'عين فارس'],
            ['wilaya_id' => 29, 'name_ar' => 'عين فراح'],
            ['wilaya_id' => 29, 'name_ar' => 'عين الحجر'],
            ['wilaya_id' => 29, 'name_ar' => 'عين خضراء'],
            ['wilaya_id' => 29, 'name_ar' => 'علايمية'],
            ['wilaya_id' => 29, 'name_ar' => 'عوف'],
            ['wilaya_id' => 29, 'name_ar' => 'بني شقران'],
            ['wilaya_id' => 29, 'name_ar' => 'بوحنيفية'],
            ['wilaya_id' => 29, 'name_ar' => 'البرج'],
            ['wilaya_id' => 29, 'name_ar' => 'بوهني'],
            ['wilaya_id' => 29, 'name_ar' => 'شرفة'],
            ['wilaya_id' => 29, 'name_ar' => 'غريس'],
            ['wilaya_id' => 29, 'name_ar' => 'الغمري'],
            ['wilaya_id' => 29, 'name_ar' => 'حسين'],
            ['wilaya_id' => 29, 'name_ar' => 'خلوية'],
            ['wilaya_id' => 29, 'name_ar' => 'ماقضة'],
            ['wilaya_id' => 29, 'name_ar' => 'مأمونية'],
            ['wilaya_id' => 29, 'name_ar' => 'محمدية'],
            ['wilaya_id' => 29, 'name_ar' => 'وادي الأبطال'],
            ['wilaya_id' => 29, 'name_ar' => 'وادي تاغية'],
            ['wilaya_id' => 29, 'name_ar' => 'أولاد بسام'],
            ['wilaya_id' => 29, 'name_ar' => 'أولاد خالد'],
            ['wilaya_id' => 29, 'name_ar' => 'أولاد مع الله'],
            ['wilaya_id' => 29, 'name_ar' => 'سيق'],
            ['wilaya_id' => 29, 'name_ar' => 'سيدي عبد الجبار'],
            ['wilaya_id' => 29, 'name_ar' => 'سيدي عبد المومن'],
            ['wilaya_id' => 29, 'name_ar' => 'سيدي علي بوسيدي'],
            ['wilaya_id' => 29, 'name_ar' => 'سيدي قادة'],
            ['wilaya_id' => 29, 'name_ar' => 'تغنيف'],
            ['wilaya_id' => 29, 'name_ar' => 'تيزي'],
            ['wilaya_id' => 29, 'name_ar' => 'زهانة'],
            ['wilaya_id' => 30, 'name_ar' => 'ورقلة'],
            ['wilaya_id' => 30, 'name_ar' => 'عين البيضاء'],
            ['wilaya_id' => 30, 'name_ar' => 'حاسي بن عبد الله'],
            ['wilaya_id' => 30, 'name_ar' => 'حاسي مسعود'],
            ['wilaya_id' => 30, 'name_ar' => 'الرويسات'],
            ['wilaya_id' => 30, 'name_ar' => 'سيدي خويلد'],
            ['wilaya_id' => 31, 'name_ar' => 'وهران'],
            ['wilaya_id' => 31, 'name_ar' => 'بئر الجير'],
            ['wilaya_id' => 31, 'name_ar' => 'عين الترك'],
            ['wilaya_id' => 31, 'name_ar' => 'أرزيو'],
            ['wilaya_id' => 31, 'name_ar' => 'بطيوة'],
            ['wilaya_id' => 31, 'name_ar' => 'مسرغين'],
            ['wilaya_id' => 31, 'name_ar' => 'السانية'],
            ['wilaya_id' => 31, 'name_ar' => 'قديل'],
            ['wilaya_id' => 31, 'name_ar' => 'بوتليليس'],
            ['wilaya_id' => 31, 'name_ar' => 'وادي تليلات'],
            ['wilaya_id' => 31, 'name_ar' => 'بوسفر'],
            ['wilaya_id' => 31, 'name_ar' => 'العنصر'],
            ['wilaya_id' => 31, 'name_ar' => 'مرسى الكبير'],
            ['wilaya_id' => 31, 'name_ar' => 'حاسي بونيف'],
            ['wilaya_id' => 31, 'name_ar' => 'حاسي بن عقبة'],
            ['wilaya_id' => 31, 'name_ar' => 'بن فريحة'],
            ['wilaya_id' => 31, 'name_ar' => 'حاسي مفسوخ'],
            ['wilaya_id' => 31, 'name_ar' => 'سيدي بن يبقى'],
            ['wilaya_id' => 31, 'name_ar' => 'عين البية'],
            ['wilaya_id' => 31, 'name_ar' => 'مرسى الحجاج'],
            ['wilaya_id' => 31, 'name_ar' => 'طفراوي'],
            ['wilaya_id' => 31, 'name_ar' => 'البرية'],
            ['wilaya_id' => 31, 'name_ar' => 'بوفاطيس'],
            ['wilaya_id' => 31, 'name_ar' => 'سيدي الشحمي'],
            ['wilaya_id' => 31, 'name_ar' => 'الكرمة'],
            ['wilaya_id' => 32, 'name_ar' => 'البيض'],
            ['wilaya_id' => 32, 'name_ar' => 'بوقطب'],
            ['wilaya_id' => 32, 'name_ar' => 'بريزينة'],
            ['wilaya_id' => 32, 'name_ar' => 'الشلالة'],
            ['wilaya_id' => 32, 'name_ar' => 'الأبيض سيدي الشيخ'],
            ['wilaya_id' => 32, 'name_ar' => 'الغاسول'],
            ['wilaya_id' => 32, 'name_ar' => 'الكاف لحمر'],
            ['wilaya_id' => 32, 'name_ar' => 'الخيثر'],
            ['wilaya_id' => 32, 'name_ar' => 'الرقاصة'],
            ['wilaya_id' => 32, 'name_ar' => 'سيدي عامر'],
            ['wilaya_id' => 32, 'name_ar' => 'سيدي سليمان'],
            ['wilaya_id' => 32, 'name_ar' => 'سيدي طيفور'],
            ['wilaya_id' => 32, 'name_ar' => 'ستيتن'],
            ['wilaya_id' => 32, 'name_ar' => 'توسمولين'],
            ['wilaya_id' => 33, 'name_ar' => 'إليزي'],
            ['wilaya_id' => 33, 'name_ar' => 'برج الحواس'],
            ['wilaya_id' => 33, 'name_ar' => 'برج عمر إدريس'],
            ['wilaya_id' => 34, 'name_ar' => 'برج بوعريريج'],
            ['wilaya_id' => 34, 'name_ar' => 'عين تاغروت'],
            ['wilaya_id' => 34, 'name_ar' => 'بليمور'],
            ['wilaya_id' => 34, 'name_ar' => 'برج غدير'],
            ['wilaya_id' => 34, 'name_ar' => 'برج زمورة'],
            ['wilaya_id' => 34, 'name_ar' => 'المنصورة'],
            ['wilaya_id' => 34, 'name_ar' => 'مجانة'],
            ['wilaya_id' => 34, 'name_ar' => 'رأس الوادي'],
            ['wilaya_id' => 34, 'name_ar' => 'سيدي مبارك'],
            ['wilaya_id' => 34, 'name_ar' => 'تيكستير'],
            ['wilaya_id' => 34, 'name_ar' => 'الياشير'],
            ['wilaya_id' => 35, 'name_ar' => 'بومرداس'],
            ['wilaya_id' => 35, 'name_ar' => 'أعفير'],
            ['wilaya_id' => 35, 'name_ar' => 'بغلية'],
            ['wilaya_id' => 35, 'name_ar' => 'بني عمران'],
            ['wilaya_id' => 35, 'name_ar' => 'برج منايل'],
            ['wilaya_id' => 35, 'name_ar' => 'بودواو'],
            ['wilaya_id' => 35, 'name_ar' => 'بودواو البحري'],
            ['wilaya_id' => 35, 'name_ar' => 'بوزقزة قدارة'],
            ['wilaya_id' => 35, 'name_ar' => 'شعبة العامر'],
            ['wilaya_id' => 35, 'name_ar' => 'دلس'],
            ['wilaya_id' => 35, 'name_ar' => 'حمادي'],
            ['wilaya_id' => 35, 'name_ar' => 'يسر'],
            ['wilaya_id' => 35, 'name_ar' => 'خميس الخشنة'],
            ['wilaya_id' => 35, 'name_ar' => 'خروبة'],
            ['wilaya_id' => 35, 'name_ar' => 'لقاطة'],
            ['wilaya_id' => 35, 'name_ar' => 'أولاد هداج'],
            ['wilaya_id' => 35, 'name_ar' => 'أولاد موسى'],
            ['wilaya_id' => 35, 'name_ar' => 'سي مصطفى'],
            ['wilaya_id' => 35, 'name_ar' => 'سيدي داود'],
            ['wilaya_id' => 35, 'name_ar' => 'سوق الأحد'],
            ['wilaya_id' => 35, 'name_ar' => 'تجلابين'],
            ['wilaya_id' => 35, 'name_ar' => 'ثنية'],
            ['wilaya_id' => 35, 'name_ar' => 'زموري'],
            ['wilaya_id' => 36, 'name_ar' => 'الطارف'],
            ['wilaya_id' => 36, 'name_ar' => 'عين العسل'],
            ['wilaya_id' => 36, 'name_ar' => 'عين الكرمة'],
            ['wilaya_id' => 36, 'name_ar' => 'بن مهيدي'],
            ['wilaya_id' => 36, 'name_ar' => 'بني صالح'],
            ['wilaya_id' => 36, 'name_ar' => 'بوحجار'],
            ['wilaya_id' => 36, 'name_ar' => 'بوقوس'],
            ['wilaya_id' => 36, 'name_ar' => 'بوثلجة'],
            ['wilaya_id' => 36, 'name_ar' => 'شبيطة مختار'],
            ['wilaya_id' => 36, 'name_ar' => 'الشط'],
            ['wilaya_id' => 36, 'name_ar' => 'الذرعان'],
            ['wilaya_id' => 36, 'name_ar' => 'العيون'],
            ['wilaya_id' => 36, 'name_ar' => 'حمام بن صالح'],
            ['wilaya_id' => 36, 'name_ar' => 'القالة'],
            ['wilaya_id' => 36, 'name_ar' => 'بحييرة الزيتون'],
            ['wilaya_id' => 36, 'name_ar' => 'رمل السوق'],
            ['wilaya_id' => 36, 'name_ar' => 'الزيتونة'],
            ['wilaya_id' => 37, 'name_ar' => 'تندوف'],
            ['wilaya_id' => 37, 'name_ar' => 'أم العسل'],
            ['wilaya_id' => 38, 'name_ar' => 'تيسمسيلت'],
            ['wilaya_id' => 38, 'name_ar' => 'عماري'],
            ['wilaya_id' => 38, 'name_ar' => 'بني شعيب'],
            ['wilaya_id' => 38, 'name_ar' => 'بني لحسن'],
            ['wilaya_id' => 38, 'name_ar' => 'برج بونعامة'],
            ['wilaya_id' => 38, 'name_ar' => 'برج الأمير عبد القادر'],
            ['wilaya_id' => 38, 'name_ar' => 'خميستي'],
            ['wilaya_id' => 38, 'name_ar' => 'لرجام'],
            ['wilaya_id' => 38, 'name_ar' => 'ليلي'],
            ['wilaya_id' => 38, 'name_ar' => 'ملعب'],
            ['wilaya_id' => 38, 'name_ar' => 'أولاد بسام'],
            ['wilaya_id' => 38, 'name_ar' => 'سيدي عابد'],
            ['wilaya_id' => 38, 'name_ar' => 'سيدي بوتوشنت'],
            ['wilaya_id' => 38, 'name_ar' => 'سيدي سليمان'],
            ['wilaya_id' => 38, 'name_ar' => 'ثنية الحد'],
            ['wilaya_id' => 38, 'name_ar' => 'يوسفي'],
            ['wilaya_id' => 39, 'name_ar' => 'الوادي'],
            ['wilaya_id' => 39, 'name_ar' => 'البياضة'],
            ['wilaya_id' => 39, 'name_ar' => 'دبيلة'],
            ['wilaya_id' => 39, 'name_ar' => 'قمار'],
            ['wilaya_id' => 39, 'name_ar' => 'حاسي خليفة'],
            ['wilaya_id' => 39, 'name_ar' => 'حساني عبد الكريم'],
            ['wilaya_id' => 39, 'name_ar' => 'كوينين'],
            ['wilaya_id' => 39, 'name_ar' => 'المقرن'],
            ['wilaya_id' => 39, 'name_ar' => 'الرقيبة'],
            ['wilaya_id' => 39, 'name_ar' => 'سيدي عون'],
            ['wilaya_id' => 39, 'name_ar' => 'تغزوت'],
            ['wilaya_id' => 39, 'name_ar' => 'ورماس'],
            ['wilaya_id' => 40, 'name_ar' => 'خنشلة'],
            ['wilaya_id' => 40, 'name_ar' => 'عين الطويلة'],
            ['wilaya_id' => 40, 'name_ar' => 'بابار'],
            ['wilaya_id' => 40, 'name_ar' => 'بوحمامة'],
            ['wilaya_id' => 40, 'name_ar' => 'ششار'],
            ['wilaya_id' => 40, 'name_ar' => 'الحامة'],
            ['wilaya_id' => 40, 'name_ar' => 'جلال'],
            ['wilaya_id' => 40, 'name_ar' => 'خيران'],
            ['wilaya_id' => 40, 'name_ar' => 'لمصارة'],
            ['wilaya_id' => 40, 'name_ar' => 'متوسة'],
            ['wilaya_id' => 40, 'name_ar' => 'أولاد رشاش'],
            ['wilaya_id' => 40, 'name_ar' => 'الرميلة'],
            ['wilaya_id' => 40, 'name_ar' => 'تاوزيانت'],
            ['wilaya_id' => 40, 'name_ar' => 'يابوس'],
            ['wilaya_id' => 41, 'name_ar' => 'سوق أهراس'],
            ['wilaya_id' => 41, 'name_ar' => 'عين الزانة'],
            ['wilaya_id' => 41, 'name_ar' => 'عين سلطان'],
            ['wilaya_id' => 41, 'name_ar' => 'بئر بوحوش'],
            ['wilaya_id' => 41, 'name_ar' => 'الدريعة'],
            ['wilaya_id' => 41, 'name_ar' => 'الحدادة'],
            ['wilaya_id' => 41, 'name_ar' => 'الحنانشة'],
            ['wilaya_id' => 41, 'name_ar' => 'الخضارة'],
            ['wilaya_id' => 41, 'name_ar' => 'المشروحة'],
            ['wilaya_id' => 41, 'name_ar' => 'المراهنة'],
            ['wilaya_id' => 41, 'name_ar' => 'مداوروش'],
            ['wilaya_id' => 41, 'name_ar' => 'أولاد دريس'],
            ['wilaya_id' => 41, 'name_ar' => 'أولاد مؤمن'],
            ['wilaya_id' => 41, 'name_ar' => 'أم العظائم'],
            ['wilaya_id' => 41, 'name_ar' => 'قصر الصبيحي'],
            ['wilaya_id' => 41, 'name_ar' => 'سدراتة'],
            ['wilaya_id' => 41, 'name_ar' => 'سيدي فرج'],
            ['wilaya_id' => 41, 'name_ar' => 'تاورة'],
            ['wilaya_id' => 41, 'name_ar' => 'تيفاش'],
            ['wilaya_id' => 41, 'name_ar' => 'ويلان'],
            ['wilaya_id' => 42, 'name_ar' => 'تيبازة'],
            ['wilaya_id' => 42, 'name_ar' => 'أحمر العين'],
            ['wilaya_id' => 42, 'name_ar' => 'عين تقورايت'],
            ['wilaya_id' => 42, 'name_ar' => 'بواسمعيل'],
            ['wilaya_id' => 42, 'name_ar' => 'بوهارون'],
            ['wilaya_id' => 42, 'name_ar' => 'بني مليك'],
            ['wilaya_id' => 42, 'name_ar' => 'بورقيقة'],
            ['wilaya_id' => 42, 'name_ar' => 'شرشال'],
            ['wilaya_id' => 42, 'name_ar' => 'الداموس'],
            ['wilaya_id' => 42, 'name_ar' => 'فوكة'],
            ['wilaya_id' => 42, 'name_ar' => 'قوراية'],
            ['wilaya_id' => 42, 'name_ar' => 'حجوط'],
            ['wilaya_id' => 42, 'name_ar' => 'حطاطبة'],
            ['wilaya_id' => 42, 'name_ar' => 'خميستي'],
            ['wilaya_id' => 42, 'name_ar' => 'كلية'],
            ['wilaya_id' => 42, 'name_ar' => 'مناصر'],
            ['wilaya_id' => 42, 'name_ar' => 'مسلمون'],
            ['wilaya_id' => 42, 'name_ar' => 'مراد'],
            ['wilaya_id' => 42, 'name_ar' => 'الناظور'],
            ['wilaya_id' => 42, 'name_ar' => 'سيدي عمار'],
            ['wilaya_id' => 42, 'name_ar' => 'سيدي غيلاس'],
            ['wilaya_id' => 42, 'name_ar' => 'سيدي راشد'],
            ['wilaya_id' => 43, 'name_ar' => 'ميلة'],
            ['wilaya_id' => 43, 'name_ar' => 'عين البيضاء أحريش'],
            ['wilaya_id' => 43, 'name_ar' => 'عين الملوك'],
            ['wilaya_id' => 43, 'name_ar' => 'عين التين'],
            ['wilaya_id' => 43, 'name_ar' => 'عميرة أراس'],
            ['wilaya_id' => 43, 'name_ar' => 'بني قشة'],
            ['wilaya_id' => 43, 'name_ar' => 'بوحاتم'],
            ['wilaya_id' => 43, 'name_ar' => 'شلغوم العيد'],
            ['wilaya_id' => 43, 'name_ar' => 'شيقارة'],
            ['wilaya_id' => 43, 'name_ar' => 'ديرة'],
            ['wilaya_id' => 43, 'name_ar' => 'القرارم قوقة'],
            ['wilaya_id' => 43, 'name_ar' => 'المنارة'],
            ['wilaya_id' => 43, 'name_ar' => 'المشيرة'],
            ['wilaya_id' => 43, 'name_ar' => 'وادي العثمانية'],
            ['wilaya_id' => 43, 'name_ar' => 'وادي النجاء'],
            ['wilaya_id' => 43, 'name_ar' => 'أولاد خلوف'],
            ['wilaya_id' => 43, 'name_ar' => 'الرواشد'],
            ['wilaya_id' => 43, 'name_ar' => 'سيدي خليفة'],
            ['wilaya_id' => 43, 'name_ar' => 'سيدي مروان'],
            ['wilaya_id' => 43, 'name_ar' => 'تاجنانت'],
            ['wilaya_id' => 43, 'name_ar' => 'تسالا لمطاع'],
            ['wilaya_id' => 43, 'name_ar' => 'تلاغمة'],
            ['wilaya_id' => 43, 'name_ar' => 'ترعي باينان'],
            ['wilaya_id' => 43, 'name_ar' => 'زغاية'],
            ['wilaya_id' => 44, 'name_ar' => 'عين الدفلى'],
            ['wilaya_id' => 44, 'name_ar' => 'عين البنيان'],
            ['wilaya_id' => 44, 'name_ar' => 'عين السلطان'],
            ['wilaya_id' => 44, 'name_ar' => 'عين تركي'],
            ['wilaya_id' => 44, 'name_ar' => 'أريب'],
            ['wilaya_id' => 44, 'name_ar' => 'بطحية'],
            ['wilaya_id' => 44, 'name_ar' => 'بلعاص'],
            ['wilaya_id' => 44, 'name_ar' => 'بومدفع'],
            ['wilaya_id' => 44, 'name_ar' => 'بوراشد'],
            ['wilaya_id' => 44, 'name_ar' => 'برج الأمير خالد'],
            ['wilaya_id' => 44, 'name_ar' => 'جليدة'],
            ['wilaya_id' => 44, 'name_ar' => 'جمعة أولاد الشيخ'],
            ['wilaya_id' => 44, 'name_ar' => 'الحمام ريغة'],
            ['wilaya_id' => 44, 'name_ar' => 'خميس مليانة'],
            ['wilaya_id' => 44, 'name_ar' => 'الماين'],
            ['wilaya_id' => 44, 'name_ar' => 'مليانة'],
            ['wilaya_id' => 44, 'name_ar' => 'المخاطرية'],
            ['wilaya_id' => 44, 'name_ar' => 'وادي الشرفة'],
            ['wilaya_id' => 44, 'name_ar' => 'وادي جمعة'],
            ['wilaya_id' => 44, 'name_ar' => 'روينة'],
            ['wilaya_id' => 44, 'name_ar' => 'سيدي لخضر'],
            ['wilaya_id' => 44, 'name_ar' => 'تاريكت'],
            ['wilaya_id' => 44, 'name_ar' => 'تيبة'],
            ['wilaya_id' => 45, 'name_ar' => 'النعامة'],
            ['wilaya_id' => 45, 'name_ar' => 'عين بن خليل'],
            ['wilaya_id' => 45, 'name_ar' => 'عين الصفراء'],
            ['wilaya_id' => 45, 'name_ar' => 'عسلة'],
            ['wilaya_id' => 45, 'name_ar' => 'جنين بورزق'],
            ['wilaya_id' => 45, 'name_ar' => 'القصدير'],
            ['wilaya_id' => 45, 'name_ar' => 'مكمن بن عمار'],
            ['wilaya_id' => 45, 'name_ar' => 'مغرار'],
            ['wilaya_id' => 45, 'name_ar' => 'صفيصيفة'],
            ['wilaya_id' => 45, 'name_ar' => 'تيوت'],
            ['wilaya_id' => 46, 'name_ar' => 'عين تموشنت'],
            ['wilaya_id' => 46, 'name_ar' => 'عين الأربعاء'],
            ['wilaya_id' => 46, 'name_ar' => 'عين الكيحل'],
            ['wilaya_id' => 46, 'name_ar' => 'عين الطلبة'],
            ['wilaya_id' => 46, 'name_ar' => 'بني صاف'],
            ['wilaya_id' => 46, 'name_ar' => 'بوزجار'],
            ['wilaya_id' => 46, 'name_ar' => 'شنتوف'],
            ['wilaya_id' => 46, 'name_ar' => 'المالح'],
            ['wilaya_id' => 46, 'name_ar' => 'الأمير عبد القادر'],
            ['wilaya_id' => 46, 'name_ar' => 'حمام بوحجر'],
            ['wilaya_id' => 46, 'name_ar' => 'حاسي الغلة'],
            ['wilaya_id' => 46, 'name_ar' => 'أولاد بوجمعة'],
            ['wilaya_id' => 46, 'name_ar' => 'أولاد كيحال'],
            ['wilaya_id' => 46, 'name_ar' => 'سيدي بن عدة'],
            ['wilaya_id' => 46, 'name_ar' => 'سيدي بومدين'],
            ['wilaya_id' => 46, 'name_ar' => 'سيدي صافي'],
            ['wilaya_id' => 46, 'name_ar' => 'تارقة'],
            ['wilaya_id' => 46, 'name_ar' => 'تيرني بني هديل'],
            ['wilaya_id' => 47, 'name_ar' => 'غرداية'],
            ['wilaya_id' => 47, 'name_ar' => 'بني يزقن'],
            ['wilaya_id' => 47, 'name_ar' => 'بونورة'],
            ['wilaya_id' => 47, 'name_ar' => 'القرارة'],
            ['wilaya_id' => 47, 'name_ar' => 'ضاية بن ضحوة'],
            ['wilaya_id' => 47, 'name_ar' => 'متليلي'],
            ['wilaya_id' => 47, 'name_ar' => 'العطف'],
            ['wilaya_id' => 47, 'name_ar' => 'زلفانة'],
            ['wilaya_id' => 48, 'name_ar' => 'غليزان'],
            ['wilaya_id' => 48, 'name_ar' => 'عين الرحمة'],
            ['wilaya_id' => 48, 'name_ar' => 'عين طارق'],
            ['wilaya_id' => 48, 'name_ar' => 'عمي موسى'],
            ['wilaya_id' => 48, 'name_ar' => 'بني درقن'],
            ['wilaya_id' => 48, 'name_ar' => 'بني زنطيس'],
            ['wilaya_id' => 48, 'name_ar' => 'بلعسل'],
            ['wilaya_id' => 48, 'name_ar' => 'بوقادير'],
            ['wilaya_id' => 48, 'name_ar' => 'دار بن عبد الله'],
            ['wilaya_id' => 48, 'name_ar' => 'جديوية'],
            ['wilaya_id' => 48, 'name_ar' => 'القلعة'],
            ['wilaya_id' => 48, 'name_ar' => 'القطار'],
            ['wilaya_id' => 48, 'name_ar' => 'لحلاف'],
            ['wilaya_id' => 48, 'name_ar' => 'مازونة'],
            ['wilaya_id' => 48, 'name_ar' => 'مديونة'],
            ['wilaya_id' => 48, 'name_ar' => 'منداس'],
            ['wilaya_id' => 48, 'name_ar' => 'المرجة سيدي عابد'],
            ['wilaya_id' => 48, 'name_ar' => 'وادي الجمعة'],
            ['wilaya_id' => 48, 'name_ar' => 'وادي خلوق'],
            ['wilaya_id' => 48, 'name_ar' => 'وادي الرهيو'],
            ['wilaya_id' => 48, 'name_ar' => 'أولاد سيدي ميهوب'],
            ['wilaya_id' => 48, 'name_ar' => 'الرمكة'],
            ['wilaya_id' => 48, 'name_ar' => 'سيدي لزرق'],
            ['wilaya_id' => 48, 'name_ar' => 'سيدي امحمد بن علي'],
            ['wilaya_id' => 48, 'name_ar' => 'سيدي امحمد بن عودة'],
            ['wilaya_id' => 48, 'name_ar' => 'سيدي سعادة'],
            ['wilaya_id' => 48, 'name_ar' => 'سوارخ'],
            ['wilaya_id' => 48, 'name_ar' => 'زمورة'],
            ['wilaya_id' => 49, 'name_ar' => 'تيميمون'],
            ['wilaya_id' => 49, 'name_ar' => 'أوقروت'],
            ['wilaya_id' => 49, 'name_ar' => 'شروين'],
            ['wilaya_id' => 49, 'name_ar' => 'دلدول'],
            ['wilaya_id' => 49, 'name_ar' => 'قصر قدور'],
            ['wilaya_id' => 49, 'name_ar' => 'مطارفة'],
            ['wilaya_id' => 49, 'name_ar' => 'طلمين'],
            ['wilaya_id' => 49, 'name_ar' => 'تينركوك'],
            ['wilaya_id' => 50, 'name_ar' => 'برج باجي مختار'],
            ['wilaya_id' => 50, 'name_ar' => 'تيمياوين'],
            ['wilaya_id' => 51, 'name_ar' => 'أولاد جلال'],
            ['wilaya_id' => 51, 'name_ar' => 'البسباس'],
            ['wilaya_id' => 51, 'name_ar' => 'الدوسن'],
            ['wilaya_id' => 51, 'name_ar' => 'الشعيبة'],
            ['wilaya_id' => 51, 'name_ar' => 'سيدي خالد'],
            ['wilaya_id' => 51, 'name_ar' => 'رأس الميعاد'],
            ['wilaya_id' => 52, 'name_ar' => 'بني عباس'],
            ['wilaya_id' => 52, 'name_ar' => 'إيغلي'],
            ['wilaya_id' => 52, 'name_ar' => 'الواتة'],
            ['wilaya_id' => 52, 'name_ar' => 'كرزاز'],
            ['wilaya_id' => 52, 'name_ar' => 'قصابي'],
            ['wilaya_id' => 52, 'name_ar' => 'أولاد خضير'],
            ['wilaya_id' => 52, 'name_ar' => 'تامترت'],
            ['wilaya_id' => 52, 'name_ar' => 'تبلبالة'],
            ['wilaya_id' => 53, 'name_ar' => 'عين صالح'],
            ['wilaya_id' => 53, 'name_ar' => 'إينغر'],
            ['wilaya_id' => 53, 'name_ar' => 'فقارة الزوى'],
            ['wilaya_id' => 54, 'name_ar' => 'عين قزام'],
            ['wilaya_id' => 54, 'name_ar' => 'تين زواتين'],
            ['wilaya_id' => 55, 'name_ar' => 'تقرت'],
            ['wilaya_id' => 55, 'name_ar' => 'بن ناصر'],
            ['wilaya_id' => 55, 'name_ar' => 'المنقر'],
            ['wilaya_id' => 55, 'name_ar' => 'المقارين'],
            ['wilaya_id' => 55, 'name_ar' => 'النزلة'],
            ['wilaya_id' => 55, 'name_ar' => 'سيدي سليمان'],
            ['wilaya_id' => 55, 'name_ar' => 'تماسين'],
            ['wilaya_id' => 55, 'name_ar' => 'طيبات'],
            ['wilaya_id' => 55, 'name_ar' => 'الزاوية العابدية'],
            ['wilaya_id' => 56, 'name_ar' => 'جانت'],
            ['wilaya_id' => 56, 'name_ar' => 'برج الحواس'],
            ['wilaya_id' => 57, 'name_ar' => 'المغير'],
            ['wilaya_id' => 57, 'name_ar' => 'جامعة'],
            ['wilaya_id' => 57, 'name_ar' => 'أم الطيور'],
            ['wilaya_id' => 57, 'name_ar' => 'سيدي خليل'],
            ['wilaya_id' => 57, 'name_ar' => 'سيدي عمران'],
            ['wilaya_id' => 57, 'name_ar' => 'تندلة'],
            ['wilaya_id' => 58, 'name_ar' => 'المنيعة'],
            ['wilaya_id' => 58, 'name_ar' => 'حاسي الفحل'],
            ['wilaya_id' => 58, 'name_ar' => 'حاسي القارة'],
        ];

        // Insert in chunks to avoid memory issues
        foreach (array_chunk($communes, 100) as $chunk) {
            DB::table('communes')->insert($chunk);
        }
    }
}
