<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ShippingCompanySeeder extends Seeder
{
    public function run(): void
    {
        $companies = [
            // الشركات الرئيسية (مع API)
            [
                'name' => 'Yalidine',
                'name_ar' => 'ياليدين',
                'code' => 'yalidine',
                'phone' => '0560 000 000',
                'email' => 'contact@yalidine.com',
                'website' => 'https://yalidine.com',
                'api_url' => 'https://api.yalidine.com/v1',
                'tracking_url_template' => 'https://yalidine.com/track/{tracking}',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'ZR Express',
                'name_ar' => 'زد آر إكسبريس',
                'code' => 'zr_express',
                'phone' => '0550 000 000',
                'email' => 'contact@zrexpress.com',
                'website' => 'https://zrexpress.com',
                'api_url' => 'https://api.zrexpress.com',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Guepex',
                'name_ar' => 'قيبكس',
                'code' => 'guepex',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Yalitec',
                'name_ar' => 'ياليتك',
                'code' => 'yalitec',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Abex Express',
                'name_ar' => 'أبكس إكسبريس',
                'code' => 'abex_express',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'ColiReli',
                'name_ar' => 'كولي ريلي',
                'code' => 'colireli',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'ISR Services',
                'name_ar' => 'ISR خدمات',
                'code' => 'isr_services',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Leopard Express',
                'name_ar' => 'ليوبارد إكسبريس',
                'code' => 'leopard_express',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'E-com Delivery',
                'name_ar' => 'إيكوم ديليفري',
                'code' => 'ecom_delivery',
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Flash Delivery',
                'name_ar' => 'فلاش ديليفري',
                'code' => 'flash_delivery',
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'NOEST Express',
                'name_ar' => 'نويست إكسبريس',
                'code' => 'noest_express',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Elogistia',
                'name_ar' => 'إيلوجيستيا',
                'code' => 'elogistia',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => '48HR Courrier Express',
                'name_ar' => '48 ساعة كورير',
                'code' => '48hr_courrier',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Anderson National Express',
                'name_ar' => 'أندرسون ناشيونال',
                'code' => 'anderson_express',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'DHD Livraison',
                'name_ar' => 'DHD ليفريزون',
                'code' => 'dhd_livraison',
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Expedia Chrono',
                'name_ar' => 'إكسبيديا كرونو',
                'code' => 'expedia_chrono',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'FRET.Direct',
                'name_ar' => 'فريت دايركت',
                'code' => 'fret_direct',
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'GoLivri',
                'name_ar' => 'قو ليفري',
                'code' => 'golivri',
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'name' => 'MSM Go',
                'name_ar' => 'MSM قو',
                'code' => 'msm_go',
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'name' => 'Rocket Delivery',
                'name_ar' => 'روكيت ديليفري',
                'code' => 'rocket_delivery',
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'name' => 'Packers World Express',
                'name_ar' => 'باكرز وورلد إكسبريس',
                'code' => 'packers_world',
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'name' => 'Negmar Express',
                'name_ar' => 'نقمار إكسبريس',
                'code' => 'negmar_express',
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'name' => 'RB Livraison',
                'name_ar' => 'RB ليفريزون',
                'code' => 'rb_livraison',
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'name' => 'AREEX Delivery',
                'name_ar' => 'أريكس ديليفري',
                'code' => 'areex_delivery',
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'name' => 'Navex Delivery',
                'name_ar' => 'نافكس ديليفري',
                'code' => 'navex_delivery',
                'is_active' => true,
                'sort_order' => 25,
            ],
            [
                'name' => 'RM Express',
                'name_ar' => 'RM إكسبريس',
                'code' => 'rm_express',
                'is_active' => true,
                'sort_order' => 26,
            ],
            [
                'name' => 'One Delivery',
                'name_ar' => 'ون ديليفري',
                'code' => 'one_delivery',
                'is_active' => true,
                'sort_order' => 27,
            ],
            [
                'name' => 'Maystro Delivery',
                'name_ar' => 'مايسترو ديليفري',
                'code' => 'maystro_delivery',
                'is_active' => true,
                'sort_order' => 28,
            ],
            [
                'name' => 'On Time Express',
                'name_ar' => 'أون تايم إكسبريس',
                'code' => 'ontime_express',
                'is_active' => true,
                'sort_order' => 29,
            ],
            [
                'name' => 'Allo Livraison',
                'name_ar' => 'ألو ليفريزون',
                'code' => 'allo_livraison',
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'name' => 'DELIVRO MAIL',
                'name_ar' => 'ديليفرو ميل',
                'code' => 'delivro_mail',
                'is_active' => true,
                'sort_order' => 31,
            ],
            [
                'name' => 'OM Courrier Express',
                'name_ar' => 'OM كورير إكسبريس',
                'code' => 'om_courrier',
                'is_active' => true,
                'sort_order' => 32,
            ],
            [
                'name' => 'Swift Express',
                'name_ar' => 'سويفت إكسبريس',
                'code' => 'swift_express',
                'is_active' => true,
                'sort_order' => 33,
            ],
            [
                'name' => 'Imir Logistics',
                'name_ar' => 'إيمير لوجيستيكس',
                'code' => 'imir_logistics',
                'is_active' => true,
                'sort_order' => 34,
            ],
            [
                'name' => 'Amana Speed Service',
                'name_ar' => 'أمانة سبيد سيرفيس',
                'code' => 'amana_speed',
                'is_active' => true,
                'sort_order' => 35,
            ],
            [
                'name' => 'Fast Delivery',
                'name_ar' => 'فاست ديليفري',
                'code' => 'fast_delivery',
                'is_active' => true,
                'sort_order' => 36,
            ],
            [
                'name' => 'Fort DZ',
                'name_ar' => 'فورت DZ',
                'code' => 'fort_dz',
                'is_active' => true,
                'sort_order' => 37,
            ],
            [
                'name' => 'RJ360 Express',
                'name_ar' => 'RJ360 إكسبريس',
                'code' => 'rj360_express',
                'is_active' => true,
                'sort_order' => 38,
            ],
            [
                'name' => 'RS Express',
                'name_ar' => 'RS إكسبريس',
                'code' => 'rs_express',
                'is_active' => true,
                'sort_order' => 39,
            ],
            [
                'name' => 'VITRANS Express',
                'name_ar' => 'فيترانس إكسبريس',
                'code' => 'vitrans_express',
                'is_active' => true,
                'sort_order' => 40,
            ],
            [
                'name' => 'JO Express',
                'name_ar' => 'JO إكسبريس',
                'code' => 'jo_express',
                'is_active' => true,
                'sort_order' => 41,
            ],
            [
                'name' => 'Time Lynx Express',
                'name_ar' => 'تايم لينكس إكسبريس',
                'code' => 'time_lynx',
                'is_active' => true,
                'sort_order' => 42,
            ],
            [
                'name' => 'Jaguar Express',
                'name_ar' => 'جاغوار إكسبريس',
                'code' => 'jaguar_express',
                'is_active' => true,
                'sort_order' => 43,
            ],
            [
                'name' => 'SBL Express',
                'name_ar' => 'SBL إكسبريس',
                'code' => 'sbl_express',
                'is_active' => true,
                'sort_order' => 44,
            ],
            [
                'name' => 'FZ Delivery',
                'name_ar' => 'FZ ديليفري',
                'code' => 'fz_delivery',
                'is_active' => true,
                'sort_order' => 45,
            ],
            [
                'name' => 'Samex Express',
                'name_ar' => 'سامكس إكسبريس',
                'code' => 'samex_express',
                'is_active' => true,
                'sort_order' => 46,
            ],
            [
                'name' => 'Chrono Rex',
                'name_ar' => 'كرونو ريكس',
                'code' => 'chrono_rex',
                'is_active' => true,
                'sort_order' => 47,
            ],
            [
                'name' => 'OVRED',
                'name_ar' => 'أوفريد',
                'code' => 'ovred',
                'is_active' => true,
                'sort_order' => 48,
            ],
            [
                'name' => 'Aranex Express',
                'name_ar' => 'أرانكس إكسبريس',
                'code' => 'aranex_express',
                'is_active' => true,
                'sort_order' => 49,
            ],
            [
                'name' => 'GS Ecommerce Express',
                'name_ar' => 'GS إيكومرس إكسبريس',
                'code' => 'gs_ecommerce',
                'is_active' => true,
                'sort_order' => 50,
            ],
            [
                'name' => 'Younex Express',
                'name_ar' => 'يونكس إكسبريس',
                'code' => 'younex_express',
                'is_active' => true,
                'sort_order' => 51,
            ],
            [
                'name' => 'KHOTWA Express',
                'name_ar' => 'خطوة إكسبريس',
                'code' => 'khotwa_express',
                'is_active' => true,
                'sort_order' => 52,
            ],
            [
                'name' => 'ULTRA Express',
                'name_ar' => 'ألترا إكسبريس',
                'code' => 'ultra_express',
                'is_active' => true,
                'sort_order' => 53,
            ],
            [
                'name' => 'MED Express',
                'name_ar' => 'ميد إكسبريس',
                'code' => 'med_express',
                'is_active' => true,
                'sort_order' => 54,
            ],
            [
                'name' => 'HHD Delivery Express',
                'name_ar' => 'HHD ديليفري إكسبريس',
                'code' => 'hhd_delivery',
                'is_active' => true,
                'sort_order' => 55,
            ],
            [
                'name' => 'ASSIL Delivery',
                'name_ar' => 'أصيل ديليفري',
                'code' => 'assil_delivery',
                'is_active' => true,
                'sort_order' => 56,
            ],
            [
                'name' => 'PDEX',
                'name_ar' => 'PDEX',
                'code' => 'pdex',
                'is_active' => true,
                'sort_order' => 57,
            ],
            [
                'name' => 'Univer Delivery',
                'name_ar' => 'يونيفر ديليفري',
                'code' => 'univer_delivery',
                'is_active' => true,
                'sort_order' => 58,
            ],
            [
                'name' => 'Royaume Delivery',
                'name_ar' => 'رويوم ديليفري',
                'code' => 'royaume_delivery',
                'is_active' => true,
                'sort_order' => 59,
            ],
            [
                'name' => 'Zimou Express',
                'name_ar' => 'زيمو إكسبريس',
                'code' => 'zimou_express',
                'is_active' => true,
                'sort_order' => 60,
            ],
        ];

        $now = now();

        foreach ($companies as $company) {
            DB::table('shipping_companies')->insert([
                'id' => Str::uuid(),
                'name' => $company['name'],
                'name_ar' => $company['name_ar'],
                'code' => $company['code'],
                'logo' => $company['logo'] ?? null,
                'phone' => $company['phone'] ?? null,
                'email' => $company['email'] ?? null,
                'website' => $company['website'] ?? null,
                'api_url' => $company['api_url'] ?? null,
                'api_key' => null,
                'api_secret' => null,
                'tracking_url_template' => $company['tracking_url_template'] ?? null,
                'volumetric_divisor' => 5000,
                'included_weight' => 5.00,
                'price_per_extra_kg' => 0,
                'is_active' => $company['is_active'],
                'sort_order' => $company['sort_order'],
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }
}
