<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SubscriptionPlan;

class SubscriptionPlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Free Trial',
                'name_ar' => 'تجريبي مجاني',
                'description' => '7 days free trial to test all features',
                'description_ar' => '7 أيام تجربة مجانية لاختبار جميع الميزات',
                'price_monthly' => 0,
                'price_yearly' => 0,
                'max_products' => 10,
                'max_orders_per_month' => 20,
                'max_staff' => 1,
                'max_categories' => 3,
                'max_images_per_product' => 3,
                'custom_domain' => false,
                'remove_branding' => false,
                'advanced_analytics' => false,
                'api_access' => false,
                'priority_support' => false,
                'facebook_pixel' => true,
                'whatsapp_integration' => false,
                'abandoned_cart' => false,
                'trial_days' => 7,
                'is_active' => true,
                'sort_order' => 0,
            ],
            [
                'name' => 'Starter',
                'name_ar' => 'بداية',
                'description' => 'Perfect for small businesses just getting started',
                'description_ar' => 'مثالي للأعمال الصغيرة التي بدأت للتو',
                'price_monthly' => 800,
                'price_yearly' => 8000,
                'max_products' => 50,
                'max_orders_per_month' => 100,
                'max_staff' => 1,
                'max_categories' => 10,
                'max_images_per_product' => 5,
                'custom_domain' => false,
                'remove_branding' => false,
                'advanced_analytics' => false,
                'api_access' => false,
                'priority_support' => false,
                'facebook_pixel' => true,
                'whatsapp_integration' => false,
                'abandoned_cart' => false,
                'trial_days' => 7,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Growth',
                'name_ar' => 'نمو',
                'description' => 'For growing businesses with more needs',
                'description_ar' => 'للأعمال المتنامية ذات الاحتياجات الأكبر',
                'price_monthly' => 1500,
                'price_yearly' => 15000,
                'max_products' => null, // Unlimited
                'max_orders_per_month' => 500,
                'max_staff' => 2,
                'max_categories' => null,
                'max_images_per_product' => 10,
                'custom_domain' => true,
                'remove_branding' => false,
                'advanced_analytics' => true,
                'api_access' => false,
                'priority_support' => false,
                'facebook_pixel' => true,
                'whatsapp_integration' => true,
                'abandoned_cart' => true,
                'trial_days' => 7,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Professional',
                'name_ar' => 'احترافي',
                'description' => 'Full features for professional sellers',
                'description_ar' => 'جميع الميزات للبائعين المحترفين',
                'price_monthly' => 3000,
                'price_yearly' => 30000,
                'max_products' => null,
                'max_orders_per_month' => 2000,
                'max_staff' => 5,
                'max_categories' => null,
                'max_images_per_product' => 15,
                'custom_domain' => true,
                'remove_branding' => true,
                'advanced_analytics' => true,
                'api_access' => true,
                'priority_support' => true,
                'facebook_pixel' => true,
                'whatsapp_integration' => true,
                'abandoned_cart' => true,
                'trial_days' => 14,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Unlimited',
                'name_ar' => 'غير محدود',
                'description' => 'No limits, no restrictions',
                'description_ar' => 'بدون حدود، بدون قيود',
                'price_monthly' => 5000,
                'price_yearly' => 50000,
                'max_products' => null,
                'max_orders_per_month' => null,
                'max_staff' => null,
                'max_categories' => null,
                'max_images_per_product' => null,
                'custom_domain' => true,
                'remove_branding' => true,
                'advanced_analytics' => true,
                'api_access' => true,
                'priority_support' => true,
                'facebook_pixel' => true,
                'whatsapp_integration' => true,
                'abandoned_cart' => true,
                'trial_days' => 14,
                'is_active' => true,
                'sort_order' => 4,
            ],
        ];

        foreach ($plans as $plan) {
            SubscriptionPlan::create($plan);
        }
    }
}
