<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ThemeSeeder extends Seeder
{
    public function run(): void
    {
        $themes = [
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Dawn',
                'name_ar' => 'فجر',
                'slug' => 'dawn',
                'description' => 'A clean, modern theme perfect for any store. Fast loading and mobile-first design.',
                'description_ar' => 'ثيم نظيف وعصري مناسب لأي متجر. تحميل سريع وتصميم متجاوب.',
                'category' => 'general',
                'thumbnail' => '/themes/dawn/thumbnail.jpg',
                'preview_url' => '/themes/dawn/preview',
                'is_free' => true,
                'price' => 0,
                'default_colors' => json_encode([
                    'primary' => '#2563eb',
                    'secondary' => '#64748b',
                    'accent' => '#f59e0b',
                    'background' => '#ffffff',
                    'text' => '#1e293b',
                    'header_bg' => '#ffffff',
                    'footer_bg' => '#1e293b',
                ]),
                'default_fonts' => json_encode([
                    'heading' => 'Cairo',
                    'body' => 'Inter',
                ]),
                'default_layout' => json_encode([
                    'header_style' => 'centered',
                    'product_grid' => 4,
                    'show_sidebar' => false,
                    'hero_style' => 'full-width',
                    'footer_columns' => 4,
                ]),
                'sections' => json_encode([
                    'hero', 'featured_products', 'categories',
                    'new_arrivals', 'testimonials', 'newsletter', 'footer',
                ]),
                'settings_schema' => json_encode([
                    'header' => ['logo_position' => 'center', 'sticky' => true, 'transparent' => false],
                    'hero' => ['height' => 'large', 'overlay' => true, 'text_align' => 'center'],
                    'products' => ['show_quick_view' => true, 'show_rating' => true],
                ]),
                'version' => '1.0.0',
                'author' => 'VPShopDZ',
                'is_active' => true,
                'installs_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Boutique',
                'name_ar' => 'بوتيك',
                'slug' => 'boutique',
                'description' => 'Elegant theme designed for fashion and clothing stores with stunning product galleries.',
                'description_ar' => 'ثيم أنيق مصمم لمتاجر الأزياء والملابس مع معارض منتجات مذهلة.',
                'category' => 'fashion',
                'thumbnail' => '/themes/boutique/thumbnail.jpg',
                'preview_url' => '/themes/boutique/preview',
                'is_free' => true,
                'price' => 0,
                'default_colors' => json_encode([
                    'primary' => '#be185d',
                    'secondary' => '#9ca3af',
                    'accent' => '#d97706',
                    'background' => '#fafafa',
                    'text' => '#111827',
                    'header_bg' => '#000000',
                    'footer_bg' => '#000000',
                ]),
                'default_fonts' => json_encode([
                    'heading' => 'Playfair Display',
                    'body' => 'Lato',
                ]),
                'default_layout' => json_encode([
                    'header_style' => 'minimal',
                    'product_grid' => 3,
                    'show_sidebar' => true,
                    'hero_style' => 'slideshow',
                    'footer_columns' => 3,
                ]),
                'sections' => json_encode([
                    'hero_slideshow', 'featured_collection', 'lookbook',
                    'categories_grid', 'instagram_feed', 'newsletter', 'footer',
                ]),
                'settings_schema' => json_encode([
                    'header' => ['logo_position' => 'left', 'sticky' => true, 'transparent' => true],
                    'hero' => ['height' => 'full', 'overlay' => true, 'text_align' => 'left'],
                    'products' => ['show_quick_view' => true, 'hover_effect' => 'zoom'],
                ]),
                'version' => '1.0.0',
                'author' => 'VPShopDZ',
                'is_active' => true,
                'installs_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'TechStore',
                'name_ar' => 'تك ستور',
                'slug' => 'techstore',
                'description' => 'Modern dark theme for electronics and tech products with specs comparison.',
                'description_ar' => 'ثيم داكن عصري للإلكترونيات والمنتجات التقنية مع مقارنة المواصفات.',
                'category' => 'electronics',
                'thumbnail' => '/themes/techstore/thumbnail.jpg',
                'preview_url' => '/themes/techstore/preview',
                'is_free' => false,
                'price' => 1500,
                'default_colors' => json_encode([
                    'primary' => '#3b82f6',
                    'secondary' => '#6b7280',
                    'accent' => '#10b981',
                    'background' => '#0f172a',
                    'text' => '#e2e8f0',
                    'header_bg' => '#1e293b',
                    'footer_bg' => '#0f172a',
                ]),
                'default_fonts' => json_encode([
                    'heading' => 'Poppins',
                    'body' => 'Roboto',
                ]),
                'default_layout' => json_encode([
                    'header_style' => 'mega-menu',
                    'product_grid' => 4,
                    'show_sidebar' => true,
                    'hero_style' => 'banner',
                    'footer_columns' => 4,
                ]),
                'sections' => json_encode([
                    'hero_banner', 'flash_deals', 'categories_icons',
                    'featured_products', 'brands', 'specs_comparison', 'footer',
                ]),
                'settings_schema' => json_encode([
                    'header' => ['logo_position' => 'left', 'sticky' => true, 'search_bar' => true],
                    'products' => ['show_specs' => true, 'show_compare' => true],
                ]),
                'version' => '1.0.0',
                'author' => 'VPShopDZ',
                'is_active' => true,
                'installs_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'FreshMarket',
                'name_ar' => 'سوق طازج',
                'slug' => 'freshmarket',
                'description' => 'Warm and inviting theme for food, grocery, and agricultural product stores.',
                'description_ar' => 'ثيم دافئ وجذاب لمتاجر الأغذية والبقالة والمنتجات الزراعية.',
                'category' => 'food',
                'thumbnail' => '/themes/freshmarket/thumbnail.jpg',
                'preview_url' => '/themes/freshmarket/preview',
                'is_free' => true,
                'price' => 0,
                'default_colors' => json_encode([
                    'primary' => '#16a34a',
                    'secondary' => '#78716c',
                    'accent' => '#ea580c',
                    'background' => '#fefce8',
                    'text' => '#1c1917',
                    'header_bg' => '#166534',
                    'footer_bg' => '#14532d',
                ]),
                'default_fonts' => json_encode([
                    'heading' => 'Nunito',
                    'body' => 'Open Sans',
                ]),
                'default_layout' => json_encode([
                    'header_style' => 'classic',
                    'product_grid' => 4,
                    'show_sidebar' => false,
                    'hero_style' => 'split',
                    'footer_columns' => 3,
                ]),
                'sections' => json_encode([
                    'hero_split', 'categories_cards', 'daily_deals',
                    'featured_products', 'farm_story', 'delivery_info', 'footer',
                ]),
                'settings_schema' => json_encode([
                    'header' => ['logo_position' => 'left', 'show_cart_icon' => true],
                    'products' => ['show_weight' => true, 'show_origin' => true],
                ]),
                'version' => '1.0.0',
                'author' => 'VPShopDZ',
                'is_active' => true,
                'installs_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'Starter',
                'name_ar' => 'ستارتر',
                'slug' => 'starter',
                'description' => 'Simple and fast one-page theme perfect for single product or landing pages.',
                'description_ar' => 'ثيم بسيط وسريع بصفحة واحدة مثالي لمنتج واحد أو صفحات الهبوط.',
                'category' => 'general',
                'thumbnail' => '/themes/starter/thumbnail.jpg',
                'preview_url' => '/themes/starter/preview',
                'is_free' => true,
                'price' => 0,
                'default_colors' => json_encode([
                    'primary' => '#7c3aed',
                    'secondary' => '#a78bfa',
                    'accent' => '#f43f5e',
                    'background' => '#ffffff',
                    'text' => '#374151',
                    'header_bg' => '#ffffff',
                    'footer_bg' => '#111827',
                ]),
                'default_fonts' => json_encode([
                    'heading' => 'Montserrat',
                    'body' => 'Source Sans Pro',
                ]),
                'default_layout' => json_encode([
                    'header_style' => 'simple',
                    'product_grid' => 3,
                    'show_sidebar' => false,
                    'hero_style' => 'centered',
                    'footer_columns' => 2,
                ]),
                'sections' => json_encode([
                    'hero_centered', 'product_showcase', 'features',
                    'testimonials', 'faq', 'cta', 'footer',
                ]),
                'settings_schema' => json_encode([
                    'header' => ['logo_position' => 'center', 'minimal' => true],
                    'products' => ['layout' => 'showcase'],
                ]),
                'version' => '1.0.0',
                'author' => 'VPShopDZ',
                'is_active' => true,
                'installs_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid()->toString(),
                'name' => 'ProServices',
                'name_ar' => 'خدمات برو',
                'slug' => 'proservices',
                'description' => 'Professional theme for service-based businesses with booking and portfolio sections.',
                'description_ar' => 'ثيم احترافي للأعمال القائمة على الخدمات مع أقسام الحجز والمعرض.',
                'category' => 'services',
                'thumbnail' => '/themes/proservices/thumbnail.jpg',
                'preview_url' => '/themes/proservices/preview',
                'is_free' => false,
                'price' => 2000,
                'default_colors' => json_encode([
                    'primary' => '#0891b2',
                    'secondary' => '#64748b',
                    'accent' => '#eab308',
                    'background' => '#f8fafc',
                    'text' => '#0f172a',
                    'header_bg' => '#0f172a',
                    'footer_bg' => '#020617',
                ]),
                'default_fonts' => json_encode([
                    'heading' => 'Raleway',
                    'body' => 'Merriweather Sans',
                ]),
                'default_layout' => json_encode([
                    'header_style' => 'professional',
                    'product_grid' => 3,
                    'show_sidebar' => false,
                    'hero_style' => 'video',
                    'footer_columns' => 4,
                ]),
                'sections' => json_encode([
                    'hero_video', 'services_grid', 'portfolio',
                    'team', 'pricing_table', 'contact_form', 'footer',
                ]),
                'settings_schema' => json_encode([
                    'header' => ['logo_position' => 'left', 'cta_button' => true],
                    'services' => ['layout' => 'cards', 'show_pricing' => true],
                ]),
                'version' => '1.0.0',
                'author' => 'VPShopDZ',
                'is_active' => true,
                'installs_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('themes')->insert($themes);
    }
}
